- src/index.js
- src/routes/Application.js
- src/routes/Results.js
Data Import landing page Scenario 2: Basic Page Layout
Added basic page layout.
Added route for results page, previous layout moved thed.
> UIDATIMP-20

- src/components/Jobs/components/PreviewsJobs/PreviewsJobs.js
Changed contracts according to /metadata-provider/jobExecutions endpoint.
> UIDATIMP-52

- CHANGELOG.md
- src/components/DataFetcher/DataFetcher.js
- src/components/DataFetcher/index.js
- src/components/ImportJobs/ImportJobs.js
- src/components/ImportJobs/components/FileUploader/FileUploader.js
- src/components/ImportJobs/components/InvalidFilesModal/InvalidFilesModal.js
- src/components/ImportJobs/components/InvalidFilesModal/index.js
- src/components/JobLogs/withJobLogsSort.js
- src/components/Jobs/components/Job/Job.js
- src/components/Jobs/components/PreviewsJobs/PreviewsJobs.js
- src/components/Jobs/components/RunningJobs/RunningJobs.js
- src/components/Jobs/jobStatuses.js
- src/components/Report/Report.js
- src/components/Report/components/RecordPreview/RecordPreview.js
- src/routes/Results.js
- src/utils/createUrl.js
- src/utils/index.js
- translations/ui-data-import/en.json
Added file extensions validation and InvalidFilesModal component for file upload.
DataFetcher and some other components was refactored.
Made some code style fixes.
JIRA ticket: https://issues.folio.org/browse/UIDATIMP-46
> UIDATIMP-46: file extensions validation and InvalidFilesModal component

- CHANGELOG.md
- src/components/ImportJobs/components/FileUploader/FileUploader.js
- src/components/ImportJobs/components/FileUploader/readme.md
- src/components/ImportJobs/components/InvalidFilesModal/InvalidFilesModal.js
- src/components/Jobs/components/Job/jobPropTypes.js
- src/components/Jobs/components/JobsList/JobsList.js
Write documentation for UI `FileUploader` component.
Refactor `FileUploader` component and some code style improvements.
JIRA ticket: https://issues.folio.org/browse/UIDATIMP-65
> UIDATIMP-65: Write documentation for UI FileUploader component

- CHANGELOG.md
- package.json
- src/components/UploadingJobsDisplay/components/FileItem/FileItem.css
- src/components/UploadingJobsDisplay/components/FileItem/FileItem.js
- src/components/UploadingJobsDisplay/components/FileItem/fileItemStatuses.js
- src/components/UploadingJobsDisplay/components/FileItem/getFileItemMeta.js
Add document icon to upload file items.
> UIDATIMP-74: Add document icon to upload file items

- src/components/ImportJobs/components/FileUploader/readme.md
Fix documentation for `FileUploader` component.
> UIDATIMP-65: fix markdown

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
> Update translation strings as of 20181228T143605

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/zh_CN.json
> Update translation strings as of 20190113T223639

- src/settings/FileExtensions/resultsFormatter.js
> UIDATIMP-47: Change dataTypes for file extension

- src/components/JobLogs/JobLogs.js
- test/bigtest/interactors/logs-pane.js
- test/bigtest/mocks/jobsLobs.js
- test/bigtest/network/scenarios/fetch-jobs-logs-success.js
- test/bigtest/tests/logs-pane-test.js
Add BigTest tests for the Landing Page Job Logs pane
**Purpose**
Improve test coverage to ensure quality.
Coverage before
Coverage after
> UIDATIMP-116

- src/components/ResultPanel/ResultPanel.css
Removed some globally targeting CSS that were causing some issues on RTL direction.
This was the original ticket: https://issues.folio.org/browse/STCOR-335
> Removed globally targeting CSS

- CHANGELOG.md
- src/components/UploadingJobsDisplay/UploadingJobsDisplay.js
Use new endpoints from mod-source-record-manager
Use new endpoints from mod-source-record-storage
> UIDATIMP-113

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/zh_CN.json
> Update translation strings as of 20190225T222207

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/zh_CN.json
> Update translation strings as of 20190227T140407

- translations/ui-data-import/ar.json
> Update translation strings as of 20190228T144944

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/zh_CN.json
> Update translation strings as of 20190306T161944

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/zh_CN.json
> Update translation strings as of 20190312T134015

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/zh_CN.json
> Update translation strings as of 20190321T130117

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/zh_CN.json
> Update translation strings as of 20190322T150534

- translations/ui-data-import/ar.json
- translations/ui-data-import/pt_BR.json
> Update translation strings as of 20190327T174151

- translations/ui-data-import/ar.json
> Update translation strings as of 20190403T132033

- CHANGELOG.md
- package.json
- src/components/FileExtensionForm/FileExtensionForm.js
- src/components/ImportJobs/ImportJobs.js
- src/components/JobProfilesForm/JobProfilesForm.js
- src/components/UploadingJobsDisplay/UploadingJobsDisplay.js
- src/settings/FileExtensions/FileExtensions.js
- src/settings/FileExtensions/ViewFileExtension.js
- src/settings/FileExtensions/resultsFormatter.js
- src/settings/JobProfiles/JobProfiles.js
- src/settings/JobProfiles/ViewJobProfile.js
- src/settings/JobProfiles/resultsFormatter.js
- src/settings/SettingPage/SettingPage.js
- test/bigtest/interactors/file-extensions.js
- test/bigtest/interactors/job-profile-details.js
- test/bigtest/interactors/job-profiles.js
- test/bigtest/network/scenarios/fetch-job-profiles-success.js
- test/bigtest/tests/file-extension-test.js
- test/bigtest/tests/job-profile-test.js
- translations/ui-data-import/en.json
Implement job profile editing feature according to requirements in the [story](https://issues.folio.org/browse/UIDATIMP-137).
>  UIDATIMP-137: Implement job profile editing feature

- src/components/SearchAndSort/SearchAndSort.js
- src/settings/JobProfiles/ViewJobProfile.js
- src/utils/constants.js
- test/bigtest/interactors/job-profile-details.js
- test/bigtest/tests/job-profile-test.js
- translations/ui-data-import/en.json
Implement job profile editing feature according to requirements in the [story](https://issues.folio.org/browse/UIDATIMP-134).
> UIDATIMP-134: Implement job profile duplicate feature

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/zh_CN.json
> Update translation strings as of 20190426T133506

- translations/ui-data-import/ar.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/pt_BR.json
> Update translation strings as of 20190429T154045

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/zh_CN.json
> Update translation strings as of 20190510T130015

- translations/ui-data-import/ar.json
> Update translation strings as of 20190510T131615

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/zh_CN.json
> Update translation strings as of 20190513T134002

- CHANGELOG.md
- src/settings/FileExtensions/FileExtensions.js
- src/settings/JobProfiles/JobProfiles.js
- src/settings/MatchProfiles/MatchProfiles.js
- src/utils/index.js
- src/utils/trimSearchTerm.js
- test/bigtest/interactors/match-profiles.js
- test/bigtest/network/scenarios/fetch-match-profiles-success.js
- test/bigtest/tests/match-profiles-test.js
Add Search box for 3rd pane of Match Profiles according to requirements in the [story](https://issues.folio.org/browse/UIDATIMP-166).
> UIDATIMP-166: Add Search box for 3rd pane of Match Profiles

- CHANGELOG.md
- src/settings/MatchProfiles/MatchProfiles.js
- src/settings/MatchProfiles/resultsFormatter.js
- test/bigtest/network/scenarios/fetch-match-profiles-success.js
- test/bigtest/tests/match-profiles/new-match-profiles-test.js
- translations/ui-data-import/en.json
> UIDATIMP-139: Save the new match profile

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/zh_CN.json
> Update translation strings as of 20190520T224011

- src/settings/MatchProfiles/MatchProfiles.js
Add match profile name in error message if the name already exists.
> UIDATIMP-139: Add match profile name in error message

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/zh_CN.json
> Update translation strings as of 20190523T143922

- translations/ui-data-import/ar.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/pt_BR.json
> Update translation strings as of 20190528T121921

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/zh_CN.json
> Update translation strings as of 20190603T125055

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/zh_CN.json
> Update translation strings as of 20190612T145704

- translations/ui-data-import/pt_BR.json
> Update translation strings as of 20190614T145022

- test/bigtest/helpers/index.js
- test/bigtest/network/scenarios/fetch-file-extensions-success.js
- test/bigtest/network/scenarios/fetch-job-profiles-success.js
- test/bigtest/network/scenarios/fetch-match-profiles-success.js
Command `stripes serve --mirage --hasAllPerms`
> Handle issue running app with mirage as the backend

- translations/ui-data-import/pt_BR.json
> Update translation strings as of 20190625T144718

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/zh_CN.json
> Update translation strings as of 20190627T152539

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/zh_CN.json
> Update translation strings as of 20190709T154346

- translations/ui-data-import/en_US.json
- translations/ui-data-import/pt_BR.json
> Update translation strings as of 20190711T172340

- translations/ui-data-import/ar.json
> Update translation strings as of 20190807T131714

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/zh_CN.json
> Update translation strings as of 20190809T200806

- translations/ui-data-import/ar.json
> Update translation strings as of 20190812T142216

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/zh_CN.json
> Update translation strings as of 20190828T124751

- translations/ui-data-import/pt_BR.json
> Update translation strings as of 20190828T202658

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/zh_CN.json
> Update translation strings as of 20190927T125508

- translations/ui-data-import/pt_BR.json
> Update translation strings as of 20191023T131908

- translations/ui-data-import/ar.json
- translations/ui-data-import/zh_TW.json
> Update translation strings as of 20191028T151017

- translations/ui-data-import/pt_BR.json
> Update translation strings as of 20191104T173556

- translations/ui-data-import/ru.json
> Update translation strings as of 20191113T152522

- src/utils/constants.js
- src/utils/fields-config.js
Correct fields labels and add missed field
https://issues.folio.org/browse/UIDATIMP-330
> UIDATIMP-330: Correct labels

- translations/ui-data-import/fr_FR.json
> Update translation strings as of 20200217T172736

- translations/ui-data-import/fr_FR.json
> Update translation strings as of 20200316T134017

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/he.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/ja.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/ru.json
- translations/ui-data-import/ur.json
- translations/ui-data-import/zh_CN.json
- translations/ui-data-import/zh_TW.json
> Update translation strings as of 20200319T202257

- translations/ui-data-import/ar.json
- translations/ui-data-import/fr_FR.json
> Update translation strings as of 20200323T195201

- CHANGELOG.md
- src/components/TreeView/TreeView.js
> UIDATIMP-411: Wipe out lines from the match profile diagram

- CHANGELOG.md
- src/components/FlexibleForm/Control.js
> UIDATIMP-426: Fix styles for the form text fields

- src/components/FlexibleForm/Control.js
- src/components/FlexibleForm/ControlDecorators/withDatePicker/withDatePicker.css
- src/components/FlexibleForm/ControlDecorators/withReferenceValues/withReferenceValues.css
> Fix styles for Select and decorators

- CHANGELOG.md
- package.json
[UIDATIMP-520](https://issues.folio.org/browse/UIDATIMP-520)
> UIDATIMP-520: Update stripes to v4

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/he.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/ja.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/ru.json
- translations/ui-data-import/ur.json
- translations/ui-data-import/zh_CN.json
- translations/ui-data-import/zh_TW.json
> Update translation strings as of 20200513T135229

- translations/ui-data-import/ru.json
> Update translation strings as of 20200615T202100

- CHANGELOG.md
- src/components/Jobs/components/Job/Job.css
- src/components/Jobs/components/Job/Job.js
- src/routes/ViewAllLogs/ViewAllLogs.js
To fix all Accessibility problems for /data-import page
- Change tag inside list from `<div>` to `<li>` in `Job` component
- Update styles
[UIDATIMP-429](https://issues.folio.org/browse/UIDATIMP-429)
> UIDATIMP-429: Fix Accessibility problems for /data-import page

- translations/ui-data-import/ru.json
> Update translation strings as of 20200624T182544

- CHANGELOG.md
- src/components/MARCTable/MARCTableRow.js
- test/bigtest/tests/mapping-profiles/new-mapping-profiles-test.js
Add validation to form fields for the Edit action.
1. Add validation functions to appropriate fields
2. Add tests
[UIDATIMP-489](https://issues.folio.org/browse/UIDATIMP-489)
[UIDATIMP-490](https://issues.folio.org/browse/UIDATIMP-490)
[UIDATIMP-491](https://issues.folio.org/browse/UIDATIMP-491)
> UIDATIMP-489 Field Mapping Profile details: MARC Bib from MARC Bib. Edit

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UISACQCOMP-3
> UISACQCOMP-3 introduce stripes deps

- CHANGELOG.md
- package.json
Increment the @folio/stripes peer-dep to ^5.0.0 for react-router
5.2.0 compatibility.
> Increment the @folio/stripes peer-dep to ^5.0.0

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/he.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/ja.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/ru.json
- translations/ui-data-import/ur.json
- translations/ui-data-import/zh_CN.json
- translations/ui-data-import/zh_TW.json
> Update translation strings as of 20200804T150835

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/he.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/ja.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/ru.json
- translations/ui-data-import/ur.json
- translations/ui-data-import/zh_CN.json
- translations/ui-data-import/zh_TW.json
> Update translation strings as of 20200807T145751

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/he.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/ja.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/ru.json
- translations/ui-data-import/ur.json
- translations/ui-data-import/zh_CN.json
- translations/ui-data-import/zh_TW.json
> Update translation strings as of 20200813T135432

- CHANGELOG.md
- src/components/UploadingJobsDisplay/UploadingJobsDisplay.js
- test/bigtest/tests/uploading-jobs-display-test.js
Remove "Edit job profile" option from Choose jobs action menu
[UIDATIMP-553](https://issues.folio.org/browse/UIDATIMP-553)
> UIDATIMP-553: Remove "Edit job profile" from Choose jobs action menu

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/he.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/ja.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/ru.json
- translations/ui-data-import/ur.json
- translations/ui-data-import/zh_CN.json
- translations/ui-data-import/zh_TW.json
> Update translation strings as of 20200904T163521

- src/components/JobLogs/JobLogs.js
- src/routes/ViewAllLogs/ViewAllLogs.js
> UIDATIMP-615: update columns order

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/he.json
- translations/ui-data-import/hi_IN.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/ja.json
- translations/ui-data-import/ko.json
- translations/ui-data-import/pl.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/ru.json
- translations/ui-data-import/ur.json
- translations/ui-data-import/zh_CN.json
- translations/ui-data-import/zh_TW.json
> Update translation strings as of 20201007T133333

- translations/ui-data-import/ar.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/pt_BR.json
> Update translation strings as of 20201008T220807

- CHANGELOG.md
- src/components/Jobs/components/Job/Job.js
- src/components/ListTemplate/ColumnTemplates/DateColumn/DateColumn.js
- src/components/ListTemplate/listTemplate.js
- src/components/MatchCriterion/view/IncomingSectionStatic/StaticValueDate.js
- src/components/MatchCriterion/view/IncomingSectionStatic/StaticValueDateRange.js
- src/components/UploadingJobsDisplay/components/FileItem/getFileItemMeta.js
- src/utils/formUtils.js
Consume FormattedDate and FormattedTime via stripes-components instead of react-intl in order to have the value prop automatically reformatted into a compliant string.
- Consume FormattedDate and FormattedTime via stripes-components instead of react-intl 
[UIDATIMP-665](https://issues.folio.org/browse/UIDATIMP-665)
> UIDATIMP-665: Data Import App: Consume {{FormattedDate}} and {{FormattedTime}} via stripes-component

- translations/ui-data-import/ar.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/he.json
- translations/ui-data-import/hi_IN.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/ja.json
- translations/ui-data-import/ko.json
- translations/ui-data-import/pl.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/ru.json
- translations/ui-data-import/ur.json
- translations/ui-data-import/zh_CN.json
- translations/ui-data-import/zh_TW.json
> Update translation strings as of 20201013T203429

- src/components/OverrideProtectedFieldsTable/OverrideProtectedFieldsTable.js
Refactor `compareFunction` for protected fields sort.
- Replace `if` conditions with `localeCompare` string method
[UIDATIMP-686](https://issues.folio.org/browse/UIDATIMP-686)
> UIDATIMP-686: Refactor `compareFunction` for protected fields sort

- package.json
[STDTC-17](https://issues.folio.org/browse/STDTC-17)
Update `stripes-data-transfer-components` to v3.0.0
> STDTC-17: Bump stripes-data-transfer-components to v3.0.0

- CHANGELOG.md
- src/routes/ViewAllLogs/ViewAllLogs.js
When a MARC bib file is imported, the options are sorted in the order of the imported records, not alphabetically.
- Add `.sort()` method for `jobProfiles` and `users` array of options.
- Fix imports order.
[UIDATIMP-601](https://issues.folio.org/browse/UIDATIMP-601)
> UIDATIMP-601: Fix jobProfiles and users dropdown options sorting

- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
> Update translation strings as of 20201016T144229

- src/components/FolioRecordTypeSelect/FolioRecordTypeSelect.js
- src/components/ListTemplate/ColumnTemplates/CheckboxColumn.js
- src/components/ListTemplate/HeaderTemplates/CheckboxHeader.js
- src/components/MARCTable/MARCTableRow.js
- src/components/MatchCriterion/edit/QualifierPartSection/QualifierPartSection.js
- src/components/MatchCriterion/edit/QualifierSection/QualifierSection.js
- src/components/ProfileTree/ProfileBranch.js
- src/components/ProfileTree/ProfileLabel.js
- src/components/ProfileTree/ProfileLinker/LinkerButton.js
- src/components/ProfileTree/ProfileLinker/ProfileLinker.js
- src/components/SearchAndSort/SearchAndSort.js
- src/components/Section/Section.js
- src/routes/ViewAllLogs/ViewAllLogsFilters.js
- src/settings/ActionProfiles/ActionProfilesForm.js
- src/settings/FileExtensions/FileExtensions.js
- src/settings/JobProfiles/JobProfilesForm.js
- src/settings/MappingProfiles/MappingProfilesForm.js
There are a bunch of warnings in the browser console, many of which are due to the wrong prop type.
> Fix console warnings

- CHANGELOG.md
- src/components/MARCTable/MARCTable.js
The fields for `MARCTable` are fetched from `redux`, and when the form is submitted, all form fields are reset, so `field` is equal to `undefined` and an error message appears.
- Check if `fields` exists, and then set it to `MARCTable` rows.
[UIDATIMP-695](https://issues.folio.org/browse/UIDATIMP-695)
> UIDATIMP-695: Fix error on saving MARC Modifications

- CHANGELOG.md
- src/components/RecordTypesSelect/components/CompareRecordSelect.js
- src/components/RecordTypesSelect/components/RecordItem.js
- src/components/RecordTypesSelect/components/RecordSelect.js
- src/components/SearchAndSort/SearchAndSort.js
- src/components/TreeView/TreeView.css
- src/components/TreeView/TreeView.js
- src/settings/MatchProfiles/ViewMatchProfile.js
To fix Accessibility problems for settings/data-import/match-profiles (lists must only directly contain li elements)
- Change attribute `id` to `data-id` to avoid duplicating id's
- Change structure according to fixes
[UIDATIMP-452](https://issues.folio.org/browse/UIDATIMP-452)
> UIDATIMP-452: Fix Accessibility problems for settings/data-import/match-profiles (lists must only directly contain li elements)

- CHANGELOG.md
- src/components/ProfileAssociator/AssociatedList.js
- src/components/ProfileAssociator/associatedProfilesColumns.js
To fix Accessibility problems for settings/data-import/action-profiles?layer=create (Buttons must have discernible text)
- Add `title` attribute to unlink profile button
https://issues.folio.org/browse/UIDATIMP-448
> UIDATIMP-448: Fix Accessibility problems for settings/data-import/action-profiles?layer=create (Buttons must have discernible text)

- CHANGELOG.md
- src/components/ProfileTree/ProfileBranch.js
- src/components/ProfileTree/ProfileLabel.js
- src/components/ProfileTree/ProfileLinker/LinkerButton.js
- src/components/ProfileTree/ProfileLinker/LinkerMenu.js
- src/components/ProfileTree/ProfileTree.js
To fix Accessibility problems in ProfileLinker Component (settings/data-import/job-profiles)
- Add unique id attributes for all places in `ProfileTree` and all related components
https://issues.folio.org/browse/UIDATIMP-434
> UIDATIMP-434: Fix Accessibility problems in ProfileLinker Component (settings/data-import/job-profiles)

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIDATIMP-738
> UIDATIMP-738 Cannot delete an import stuck in "Running"

- package.json
https://issues.folio.org/browse/UIDATIMP-738
> UIDATIMP-738 additional permission has been added according comment

- CHANGELOG.md
- src/components/JobLogs/withJobLogsSort.js
https://issues.folio.org/browse/UIDATIMP-741
> UIDATIMP-741 Attempt to sort JobLogs table by status leads to error

- CHANGELOG.md
- src/components/TreeView/TreeView.css
https://issues.folio.org/browse/UIDATIMP-739
> UIDATIMP-739 Match profiles are misaligned and have a stray line in them

- CHANGELOG.md
- src/components/WithValidation/WithValidation.js
- src/components/WithValidation/index.js
- src/components/index.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/Acquisition.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/AdministrativeData.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/ElectronicAccess.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/HoldingsDetails.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/HoldingsNotes.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/Location.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/ReceivingHistory.js
- src/settings/MappingProfiles/detailsSections/edit/InstanceDetailsSections/InstanceRelationship.js
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/AdministrativeData.js
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/Condition.js
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/ElectronicAccess.js
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/EnumerationData.js
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/ItemData.js
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/ItemNotes.js
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/LoanAndAvailability.js
- src/utils/formValidators.js
- translations/ui-data-import/en.json
When default data (non-MARC field) is added to a field mapping profile, it must be enclosed in quotation marks. If the value is selected from a dropdown, the quotation marks are added automatically. If the value is typed by the user, no quotation marks are added, and no validation error appears.
- Add `validateDefaultDataTypedInField` function
- Update `validateForQuotedStringOrMarcPathPattern` function
- Create `WithValidation` wrapper component
- Wrap all needed field with current component
https://issues.folio.org/browse/UIDATIMP-746
> UIDATIMP-746: Validation for default data typed into a field mapping profile is not working

- translations/ui-data-import/ar.json
- translations/ui-data-import/ber.json
- translations/ui-data-import/ca.json
- translations/ui-data-import/da.json
- translations/ui-data-import/de.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
- translations/ui-data-import/es.json
- translations/ui-data-import/es_419.json
- translations/ui-data-import/es_ES.json
- translations/ui-data-import/fr.json
- translations/ui-data-import/fr_FR.json
- translations/ui-data-import/he.json
- translations/ui-data-import/hi_IN.json
- translations/ui-data-import/hu.json
- translations/ui-data-import/it_IT.json
- translations/ui-data-import/ja.json
- translations/ui-data-import/ko.json
- translations/ui-data-import/pl.json
- translations/ui-data-import/pt_BR.json
- translations/ui-data-import/pt_PT.json
- translations/ui-data-import/ru.json
- translations/ui-data-import/ur.json
- translations/ui-data-import/zh_CN.json
- translations/ui-data-import/zh_TW.json
> Update translation strings as of 20201110T192302

- CHANGELOG.md
- src/components/ListTemplate/searchAndSortTemplate.js
- src/components/ProfileAssociator/AssociatorStatic.js
An error occurred while searching for associated profiles in an action profile.
- Add optional chaining operator to search by `tags`.
- Make search case insensitive.
[UIDATIMP-769](https://issues.folio.org/browse/UIDATIMP-769)
> UIDATIMP-769: Fix an error occurred while searching for associated profiles

- CHANGELOG.md
- src/components/ProfileAssociator/AssociatorStatic.js
- src/components/SearchAndSort/SearchAndSort.css
- src/components/SearchAndSort/SearchAndSort.js
To reuse `<SearchForm>` component from `stripes-data-transfer-components` rep
[UIDATIMP-582](https://issues.folio.org/browse/UIDATIMP-582)
> UIDATIMP-582: Reuse `<SearchForm>` component from `stripes-data-transfer-components` rep

- CHANGELOG.md
- package.json
> Release v3.0.3

- CHANGELOG.md
- src/utils/formValidators.js
- translations/ui-data-import/en.json
For repeatable fields in the Instance, Holdings, and Item field mapping profiles, if you select an action first, FOLIO validates whether you add a value, or (if the action is remove all) does not allow you to add a value. If you add the value first (before selecting an action), the field mapping profile can be saved without an action for the repeatable field. And then the import errors because FOLIO does not know what action to take for the repeatable field.
-Add validation rule for `RepeatableActionsField` component
https://issues.folio.org/browse/UIDATIMP-768
> UIDATIMP-768: Field mapping for repeatable fields needs a tweak to validation

- CHANGELOG.md
- src/components/Callout/Callout.test.js
- src/components/Callout/NetworkMessage.test.js
To Cover `<Callout>` component with tests
- Add `Callout.test.js ` for createNetworkMessage function
- Add `NetworkMessage.test.js ` for NetworkMessage component
https://issues.folio.org/browse/UIDATIMP-701
> UIDATIMP-701: Cover Callout component with tests

- CHANGELOG.md
- src/components/DataFetcher/DataFetcher.test.js
- test/bigtest/interactors/search-and-sort-pane.js
- test/bigtest/tests/view-all-logs-test.js
To Cover `<DataFetcher>` component with tests
- Add `DataFetcher.test.js` for DataFetcher component
- removed unnecessary fields and renamed `resetButton`  according to changes in [STSMACOM-465](https://issues.folio.org/browse/STSMACOM-465)
https://issues.folio.org/browse/UIDATIMP-703
> UIDATIMP-703: Cover DataFetcher component with test

- CHANGELOG.md
- src/routes/ViewAllLogs/ViewAllLogs.js
To have a possibility to go to the Log lite page from View all page
- Remove onRowClick handler from row in `ViewAllLogs` component
- Add required URL to fileName button in `ViewAllLogs` component
https://issues.folio.org/browse/UIDATIMP-762
> UIDATIMP-762: Log lite - import job summary page, from View all page

- CHANGELOG.md
- src/components/RecordTypesSelect/components/IncomingRecordMenu.js
- src/components/RecordTypesSelect/components/RecordItem.js
- src/settings/JobProfiles/JobProfilesForm.js
- src/utils/constants.js
To enable EDIFACT invoice options in various settings (except the match profiles)
[UIDATIMP-778](https://issues.folio.org/browse/UIDATIMP-778)
> UIDATIMP-778: Enable EDIFACT invoice options in various settings

- CHANGELOG.md
- src/components/MatchCriterion/edit/ExistingRecordSections/ExistingSectionFolio.js
- src/components/MatchCriterion/edit/MatchCriterion.js
- src/settings/MatchProfiles/MatchProfilesForm.js
Add validation to the "Existing record" details section
- Wrap `Selection` component into `Field` component and add pre- and post- saving to Redux methods
- Add validation to this required field
[UIDATIMP-782](https://issues.folio.org/browse/UIDATIMP-782)
> UIDATIMP-782: Add validation to "Existing record" details section

- CHANGELOG.md
- src/settings/MappingProfiles/MappingProfilesForm.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceAdjustments.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceLineAdjustments.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceLineFundDistribution.js
- src/settings/MappingProfiles/detailsSections/edit/MappingInvoiceDetails.js
- src/utils/constants.js
- src/utils/shapes.js
Add dependency for all toggles in Field mapping Invoice Details accordions on Currency select in
Extended information accordion
- Get value of currency field from redux-form state and pass it to related accordions
- Apply currency prop to `TypeToggle`  components
https://issues.folio.org/browse/UIDATIMP-801
> UIDATIMP-801: Toggles should display currency selected in Currency select in Extended information accordion

- CHANGELOG.md
- src/components/AcceptedValuesField/AcceptedValuesField.js
- src/components/withReferenceValues/withReferenceValues.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceInformation.js
- src/utils/formUtils.js
To extend functionality of AcceptedValuesField component to be able to choose several option in "Acquisitions units" field in Invoice information accordion
- Add `isMultiSelection` prop to `AcceptedValuesField` and `withReferenceValues` components
- Update behaviour of `formatDecoratorValue` function
https://issues.folio.org/browse/UIDATIMP-803
> UIDATIMP-803: Extend functionality of AcceptedValuesField component to be able to choose several option

- CHANGELOG.md
- package.json
- src/components/AcceptedValuesField/AcceptedValuesField.js
- src/components/FieldOrganization/FieldOrganization.js
- src/components/FieldOrganization/index.js
- src/components/OptionsList/OptionsList.js
- src/components/index.js
- src/components/withReferenceValues/withReferenceValues.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceLineInformation.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/VendorInformation.js
- src/settings/MappingProfiles/detailsSections/edit/MappingInvoiceDetails.js
- src/settings/MappingProfiles/detailsSections/utils.js
- src/settings/MappingProfiles/initialDetails/INVOICE.js
- src/utils/constants.js
To implement functionality for "Vendor name" and "Accounting code" fields for Vendor information accordion
- Create new component `FieldOrganization` for Vendor name Field connected to Organization plugin
- Update `OptionsList` component to display Empty message in case when there are no date for options
- Update logic for displaying `account Number` Field (free text field or With reference values field depend on the Selected vendor)
- Add required fields to `VendorInformation` section
- Add `getFieldValueFromDetails` and `getAccountingNumberOptions ` functions for getting relevant data
https://issues.folio.org/browse/UIDATIMP-800
> UIDATIMP-800: Create functionality for "Vendor name" and "Accounting code" fields for Vendor information accordion

- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceLineFundDistribution.js
- src/settings/MappingProfiles/initialDetails/INVOICE.js
fix according comment
https://issues.folio.org/browse/UIDATIMP-811
> UIDATIMP-811 fix according comment

- CHANGELOG.md
- src/components/MatchCriterion/edit/ExistingRecordSections/ExistingSectionFolio.js
Cannot create match profile when trying to match an incoming MARC Bib to any field in Instance, Holdings, or Item record
- Update `handleExistingRecordSelect` function in `ExistingSectionFolio` component
https://issues.folio.org/browse/UIDATIMP-821
> UIDATIMP-821: Cannot create match profile

- CHANGELOG.md
- package.json
- src/components/SearchAndSort/SearchAndSort.js
- src/settings/FileExtensions/FileExtensionForm.js
- src/utils/formUtils.js
Refactor File Extensions view to use final-form instead of redux-form
- Update `FileExtensionForm` component to use stripes-final-form instead of redux-form
- Update dependencies in `package.json`
- Add `composeValidators` helper function to use multiple validation for one field
https://issues.folio.org/browse/UIDATIMP-825
> UIDATIMP-825: Refactor File Extensions view to use final-form instead of redux-form

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIDATIMP-840
> UIDATIMP-840 - Update stripes-cli to v2

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/ExtendedInformation.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceAdjustments.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceInformation.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceLineAdjustments.js
To remove the validation from fields with ref values from the Invoice field mapping profile to be able to save a profile.
- Pass custom empty validation to the `AcceptedValuesField` component
https://issues.folio.org/browse/UIDATIMP-855
> UIDATIMP-855: Remove validation from fields with reference values

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceInformation.js
- src/settings/MappingProfiles/detailsSections/edit/MappingInvoiceDetails.js
- src/utils/constants.js
When the "Lock total" checkbox is checked in the Invoice field mapping profile, the check is not saved.
- Add `hasLockTotal` prop to `InvoiceInformation` component to use as default value for `useState`
https://issues.folio.org/browse/UIDATIMP-857
> UIDATIMP-857: Invoice field mapping: Lock total checkbox is not working properly

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/ExtendedInformation.js
- src/settings/MappingProfiles/detailsSections/edit/MappingInvoiceDetails.js
- src/utils/constants.js
When the checkbox for "Use set exchange rate" is checked, it is not saved.
- Add `hasExchangeRate` prop to `ExtendedInformation` component to use as default value for useState
https://issues.folio.org/browse/UIDATIMP-864
> UIDATIMP-864: Invoice field mapping: Exchange rate checkbox is not being saved

- CHANGELOG.md
- PERSONAL_DATA_DISCLOSURE.md
Place a copy of the personal data disclosure form at the top level of the module github repository and check the boxes that apply.
https://issues.folio.org/browse/UIDATIMP-786
> UIDATIMP-786 Add personal data disclosure form

- CHANGELOG.md
- src/components/FieldOrganization/FieldOrganization.js
- src/settings/MappingProfiles/detailsSections/view/MappingInvoiceDetails.js
Adjust "vendor name" field value
- Wrap vendorId sending in request into quoptation marks
https://issues.folio.org/browse/UIDATIMP-868
> UIDATIMP-868: Adjust vendor name field value

- src/settings/MappingProfiles/initialDetails/INVOICE.js
Additional changes for https://github.com/folio-org/ui-data-import/pull/856
- Change Initial field enabled for status field to 'true'
https://issues.folio.org/browse/UIDATIMP-868
> UIDATIMP-868: Adjust vendor name field value. Additional chabges

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIDATIMP-872
> UIDATIMP-872 Update module permission for logs retrieving

- CHANGELOG.md
- src/components/JobLogsContainer/JobLogsContainer.js
When records are posted directly to SRS via the API, they do not have a file name.
Thus, the log information is difficult to access. This task ensures a default for the file name on the landing page for the records that were posted via API.
- Add `No file name` text when `fileName` field of the job is absence
https://issues.folio.org/browse/UIDATIMP-873
> UIDATIMP-873: Ensure file name info for records posted direct via APIon landing page

- CHANGELOG.md
- src/routes/JobSummary/JobSummary.js
- src/routes/JobSummary/JobSummary.test.js
To provide a lite summary for an EDIFACT invoice import
- Check data type, if it is equal to `EDIFACT` then
- show `invoice` icon in the header
- show `record order` as it is
- For `MARC` type increment `record order`
https://issues.folio.org/browse/UIDATIMP-816
> UIDATIMP-816: Log lite: Import job summary for EDIFACT invoices

- src/components/OverrideProtectedFieldsTable/OverrideProtectedFieldsTable.js
To make the accordions in the MARC update field mapping profile more responsive and efficient
- Fix logic for open/close state of accordion depending on checked override protected field
https://issues.folio.org/browse/UIDATIMP-858
> UIDATIMP-858: MARC Updates field mapping profile: be able to collapse/expand accordions (fix 2nd scenario)

- CHANGELOG.md
- src/components/JobLogsContainer/JobLogsContainer.test.js
Cover <JobLogsContainer> component with tests using RTL+Jest.
- Cover `JobLogsContainer` component with unit tests
https://issues.folio.org/browse/UIDATIMP-713
> UIDATIMP-713: Cover <JobLogsContainer> component with tests

- CHANGELOG.md
- src/components/ListTemplate/ActionIcon.test.js
- src/components/ListTemplate/listTemplate.test.js
- src/components/ListTemplate/searchAndSortTemplate.js
- src/components/ListTemplate/searchAndSortTemplate.test.js
Cover <ListTemplate> component with tests using RTL+Jest.
- Cover `ActionIcon` component with test
- Cover `listTemplate` component with test
- Cover `searchAndSortTemplate` component with test and fix logic of parsing message
https://issues.folio.org/browse/UIDATIMP-707
> UIDATIMP-707: Cover <ListTemplate> component with tests

- CHANGELOG.md
- src/components/LogViewer/LogViewer.js
- src/routes/ViewJobLog.js
When clicking on a row in the log summary for an imported MARC file, that should display the details for that particular record. Instead, I'm getting an error screen, with details that reference invoices.
- Add check whether `relatedInvoiceLineInfo` field exists
https://issues.folio.org/browse/UIDATIMP-903
> UIDATIMP-903: Iris Bugfest: Error when trying to view the record-level details in the import log

- CHANGELOG.md
- src/components/ImportJobs/ImportJobs.js
- src/components/ImportJobs/components/getErrorModalMeta.js
- translations/ui-data-import/en.json
Files without file extensions may contain executables or malware. We would like to disallow them from being uploaded to begin a Data import process
- Add check on file extension when `onDrop` method is called
https://issues.folio.org/browse/UIDATIMP-896
> UIDATIMP-896: Disallow the upload of files without file extensions

- CHANGELOG.md
- src/routes/JobSummary/JobSummary.js
- src/routes/ViewJobLog.js
When a user runs an import job and then tries to view the log, an unfriendly "Failed to get" error message displays if there was a create error. This error message should be suppressed, since the user will see details of the error in the log.
- Fix misspelling
https://issues.folio.org/browse/UIDATIMP-905
> UIDATIMP-905: Error popup displays when trying to view log when there is an error

- CHANGELOG.md
- src/components/DetailsKeyShortcutsWrapper/DetailsKeyShortcutsWrapper.js
- src/components/DetailsKeyShortcutsWrapper/index.js
- src/components/EditKeyShortcutsWrapper/EditKeyShortcutsWrapper.js
- src/components/EditKeyShortcutsWrapper/index.js
- src/components/SearchAndSort/SearchAndSort.js
- src/components/index.js
- src/index.js
- src/settings/JobProfiles/JobProfilesForm.js
- src/settings/JobProfiles/ViewJobProfile.js
Each FOLIO app should support these baseline shortcut keys (when applicable).
- Implement `DetailsKeyShortcutsWrapper` and `EditKeyShortcutsWrapper` wrappers
- Provide handlers for shorcut keys
https://issues.folio.org/browse/UIDATIMP-898
> UIDATIMP-898: Data Import Settings > Apply baseline shortcut keys for Job profile

- CHANGELOG.md
- Jenkinsfile
- package.json
https://issues.folio.org/browse/UIDATIMP-888
> UIDATIMP-888 - Compile Translation Files into AST Format

- CHANGELOG.md
- src/settings/ActionProfiles/ActionProfilesForm.js
- src/settings/ActionProfiles/ViewActionProfile.js
Each FOLIO app should support these baseline shortcut keys (when applicable).
https://issues.folio.org/browse/UIDATIMP-900
> UIDATIMP-900: Data Import Settings > Apply baseline shortcut keys for Action profile

- CHANGELOG.md
- src/settings/JobProfiles/ViewJobProfile.js
https://issues.folio.org/browse/UIDATIMP-925
> UIDATIMP-925: Cannot run a data import job in any of the hosted ref envs

- CHANGELOG.md
- src/components/ProfileTree/ProfileTree.js
- src/settings/JobProfiles/JobProfilesForm.js
If a user is creating or editing a job profile and links an action profile, then unlinks it, sometimes it does not unlink.
- Save relations to the component state
https://issues.folio.org/browse/UIDATIMP-910
> UIDATIMP-910: Fix action profiles that have been unlinked from job profiles sometimes reappear

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIDATIMP-943
> UIDATIMP-943 - Expand module permissions with permissions for preceding and succeeding titles

- CHANGELOG.md
- src/routes/JobSummary/JobSummary.js
- src/routes/ViewJobLog.js
- src/settings/FileExtensions/FileExtensionForm.js
- src/settings/JobProfiles/JobProfilesForm.js
- src/utils/constants.js
This reverts commit c79e862e
Due to changes in the backend dataType enum schema, it is needed to change `MARC_BIB` type to `MARC` for Job profiles and File extensions.
https://issues.folio.org/browse/UIDATIMP-944
> Revert "UIDATIMP-917: Rename constant "MARC" to "MARC_BIB" (#910)"

- CHANGELOG.md
- src/components/WithTranslation/WithTranslation.test.js
- test/jest/babel.config.js
Cover `<WithTranslation>` component with unit tests using RTL+Jest
- Cover `<WithTranslation>` component with unit tests
- Add bubel config rule to avoid warnings in the console output
https://issues.folio.org/browse/UIDATIMP-733
> UIDATIMP-733: Cover `<WithTranslation>` component with unit tests

- CHANGELOG.md
- src/routes/JobSummary/JobSummary.js
Sometimes, the user is sent to an unexpected screen when closing the summary log.
- Navigate to /data-import any time when closing JobSummary page
https://issues.folio.org/browse/UIDATIMP-949
> UIDATIMP-949: Navigate to /data-import when closing JobSummary page

- CHANGELOG.md
- src/components/ProfileAssociator/AssociatorEditable.js
- src/settings/ActionProfiles/ActionProfilesForm.js
When linking a new field mapping profile to an action profile then unlinking it and linking some another and save the action profile, 2 field mapping profiles are actually linked to the profile, which then causes the job to error.
- Remove unlinked profiles from `addedRelations` array as well on unlinking
https://issues.folio.org/browse/UIDATIMP-931
> UIDATIMP-931: Fix 1 action profile has 2 field mappings attached to it

- CHANGELOG.md
- src/components/TreeView/TreeView.test.js
UIDATIMP-728 Cover <TreeView> component with tests
Cover the module with unit test cases and 100% coverage
> UIDATIMP-728 Cover <TreeView> component with tests

- CHANGELOG.md
- src/components/withReferenceValues/withReferenceValues.test.js
Cover withReferenceValues component with unit tests using RTL + Jest
Covered withReferenceValues component with unit tests using RTL + Jest
https://issues.folio.org/browse/UIDATIMP-732
> UIDATIMP-732: Cover <withReferenceValues> component with unit tests

- CHANGELOG.md
- src/components/RepeatableActionsField/RepeatableActionsField.test.js
Cover RepeatActionsField component with tests using RTL+Jest.
Covered RepeatActionsField component with unit tests using Jest + RTL
https://issues.folio.org/browse/UIDATIMP-722
> UIDATIMP-722: Cover <RepeatableActionsField> component with unit tests

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/MappingInvoiceDetails.js
EDIFACT invoices fail to import properly due to an empty "value" field even though `enabled` field is `true`
- Set `enabled` filed to `false` when there is no value
https://issues.folio.org/browse/UIDATIMP-1005
> UIDATIMP-1005: EDIFACT invoices fail to import properly due to invalid "value"

- src/components/RecordTypesSelect/components/RecordSelect.js
- src/routes/Home.js
> Fix imports

- CHANGELOG.md
- src/routes/JobSummary/JobSummary.js
JSON for MARC records never resolves
- Add check in EDIFACT type
https://issues.folio.org/browse/UIDATIMP-1018
> UIDATIMP-1018: Error getting metadata for record

- CHANGELOG.md
- src/routes/JobSummary/JobSummary.js
- src/routes/JobSummary/JobSummary.test.js
Populate Record Log title column when imported record is MARC Holdings.
Issue: [UIDATIMP-1007](https://issues.folio.org/browse/UIDATIMP-1007)
> UIDATIMP-1007: Data Import > Record Log Updates when imported record is MARC | What to populate in title column

- CHANGELOG.md
- package.json
- src/components/MatchCriterion/edit/ExistingRecordSections/ExistingSectionFolio.test.js
> Release v5.0.2

- src/settings/MARCFieldProtection/MARCFieldProtection.js
To allow `*` to be entered to the `field` field
- Adjust UI validation for the field
https://issues.folio.org/browse/UIDATIMP-1043
> UIDATIMP-1043: Adjust UI for the Field protection create/edit screen

- CHANGELOG.md
- src/components/SearchAndSort/SearchAndSort.js
- src/components/SearchAndSort/SearchAndSort.test.js
UIDATIMP-723: Cover SearchAndSort component with tests
UIDATIMP-723: Covered SearchAndSort component with tests using Jest + RTL
https://issues.folio.org/browse/UIDATIMP-723
> UIDATIMP-723: Cover `<SearchAndSort>` component with tests

- CHANGELOG.md
- src/components/ImportJobs/ImportJobs.test.js
- src/components/ImportJobs/components/getErrorModalMeta.test.js
- src/components/MatchCriterion/edit/ExistingRecordSections/ExistingSectionFolio.test.js
- src/index.test.js
- src/routes/ViewAllLogs/ViewAllLogs.test.js
- src/settings/JobProfiles/tests/JobProfilesForm.test.js
- src/settings/MappingProfiles/tests/MappingProfiles.test.js
- src/settings/MappingProfiles/tests/MappingProfilesForm.test.js
- src/settings/MappingProfiles/tests/ViewMappingProfile.test.js
* Enable skipped test for <ExistingSection> component and check overall test coverage of ui-data-import.
* Ensure testing coverage for this code is 80% plus and confirm with a screenshot.
* Cover `MappingProfiles` settings with tests using RTL + Jest.
- Enable skipped test for <ExistingSection> component
- Increase test coverage for other components
- Cover `MappingProfiles` settings with tests using RTL + Jest.
https://issues.folio.org/browse/UIDATIMP-1065
Run tests
Code coverage report
> UIDATIMP-1065: Enable skipped test for <ExistingSection> component and check overall test coverage of ui-data-import

- CHANGELOG.md
- package.json
- src/components/DataFetcher/DataFetcher.js
- src/utils/createUrlFromArray.js
- src/utils/index.js
- src/utils/tests/createUrlFromArray.test.js
- test/jest/babel.config.js
Use new API for DataImport landing page
createUrlFromArray function has been added to handle lists with same params
https://issues.folio.org/browse/UIDATIMP-819
> UIDATIMP-918 - Use new API for DataImport landing page

- CHANGELOG.md
- src/settings/MappingProfiles/ViewMappingProfile.js
Field mapping profiles created by auto tests couldn't be viewed
- Add default values to undefined props
https://issues.folio.org/browse/UIDATIMP-1073
> UIDATIMP-1073: Field mapping profiles created by auto tests couldn't be viewed

- CHANGELOG.md
- src/settings/DataImportSettings/DataImportSettings.js
Move focus to the Data Import pane header when selecting Data Import under the list of Settings
Added ref to the Settings page
https://issues.folio.org/browse/UIDATIMP-1085
<!-- OPTIONAL
One picture is literally worth a thousand words. When the feature is
an interaction, an animated GIF is best. Most of the time it helps to
include "before" and "after" screenshots to quickly demonstrate the
value of the feature.
Here are some great tools to help you record gifs:
Windows: https://getsharex.com/
Mac: https://gifox.io/
--
https://user-images.githubusercontent.com/85172747/151336479-c4418a18-08f5-4ea0-8559-c4c56cdd7cac.mp4
>
> UIDATIMP-1085: Settings > Data Import > change focus

- CHANGELOG.md
- package.json
changelog update after release
> Release v5.0.4

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/view/HoldingsDetailsSections/AdministrativeData.js
To add Data Import support for the Administrative note field that was added to the Inventory Holdings
Added ViewRepeatableField component for Administrative notes
https://issues.folio.org/browse/UIDATIMP-1122
> UIDATIMP-1122 - Add Admin note field to the Holdings field mapping profile: View

- CHANGELOG.md
- src/routes/ViewAllLogs/ViewAllLogs.js
- src/routes/ViewAllLogs/ViewAllLogs.test.js
- src/routes/ViewAllLogs/ViewAllLogsUtils.js
Fix unit tests for the ViewAllLogs component
[UIDATIMP-1151](https://issues.folio.org/browse/UIDATIMP-1151)
> UIDATIMP-1151: Fix unit tests for the ViewAllLogs component

- CHANGELOG.md
- src/routes/JobSummary/JobSummary.js
- src/routes/JobSummary/JobSummary.test.js
- src/routes/JobSummary/components/RecordsTable.js
- src/routes/JobSummary/components/RecordsTable.test.js
- src/routes/JobSummary/components/SummaryTable.js
- src/routes/JobSummary/components/SummaryTable.test.js
- src/routes/JobSummary/components/index.js
Add a summary at the top of an import job's list of records
- Split RecordsTable and SummaryTable
- Fill the SummaryTable with NoValue until the endpoint is ready
- Cover new code with tests
https://issues.folio.org/browse/UIDATIMP-1153
> UIDATIMP-1153: Add summary at top of individual import job's log

- CHANGELOG.md
- src/routes/JobSummary/components/SummaryTable.js
- src/routes/JobSummary/components/SummaryTable.test.js
-  Accessibility check: Individual job log screen
- Ensure every id attribute is unique
- https://issues.folio.org/browse/UIDATIMP-1154
> UIDATIMP-1154: Accessibility check: Individual job log screen

- CHANGELOG.md
- src/components/ProfileTree/ProfileBranch.js
- src/routes/JobSummary/JobSummary.js
- src/routes/JobSummary/components/SummaryTable.js
- src/routes/JobSummary/components/SummaryTable.test.js
Connect summary table of import job's log to BE
- Use new API to get job execution summary data
- Add tests
https://issues.folio.org/browse/UIDATIMP-1163
> UIDATIMP-1163: Connect summary table of import job's log to BE

- CHANGELOG.md
- src/routes/ViewAllLogs/ViewAllLogs.js
- src/routes/ViewAllLogs/ViewAllLogs.test.js
Add job profiles into job profile filter for all the imported records on View all logs page
Used endpoint to get all the job profiles, which were used for importing jobs
https://issues.folio.org/browse/UIDATIMP-1177
https://user-images.githubusercontent.com/85172747/171020981-1db0ceec-d0bb-4248-958c-7e05c5807499.mp4
> UIDATIMP-1177: View all logs: Job profile filter contains only profiles displayed on a specific page

- CHANGELOG.md
- src/components/ListTemplate/ColumnTemplates/CheckboxColumn.js
- src/components/ListTemplate/HeaderTemplates/CheckboxHeader.js
- src/components/ListView/ListView.js
- src/components/SearchAndSort/SearchAndSort.js
- src/settings/MatchProfiles/MatchProfiles.js
- Check for accessibility issues on updated match screens
- https://issues.folio.org/browse/UIDATIMP-1052
> UIDATIMP-1052: Check for accessibility issues on updated match screens

- CHANGELOG.md
- src/routes/JobSummary/JobSummary.js
- src/routes/JobSummary/components/SummaryTable.js
- src/routes/JobSummary/components/SummaryTable.test.js
Make the error counts in the individual job summary hotlinks, so that the list of records in the file can be filtered to only show particular errors
- Make each error value a hotlink, except if the value is 0
- Filter records by `errorsOnly` and `entity`
- Cover new code with unit tests
https://issues.folio.org/browse/UIDATIMP-1158
> UIDATIMP-1158: Add error hotlinks to the summary at top of individual import job's log

- CHANGELOG.md
* Update `Data import/View all` to persist `session/local storage` of the `search/filter pane` collapsed/uncollapsed
* Added new check in `SearchAndSort` component ([See related ticket](https://issues.folio.org/browse/STSMACOM-677))
[UIDATIMP-979]( https://issues.folio.org/browse/UIDATIMP-979)
https://user-images.githubusercontent.com/85172747/175499615-7e75b7d2-d2ef-4e1d-a1e1-7960da726cf3.mp4
> UIDATIMP-979: Resizable Panes - Persistence | Use PersistedPaneset smart component for Data import/View all page

- CHANGELOG.md
- src/settings/JobProfiles/JobProfiles.js
- Improve cql query to get job profiles for further import processing
- Use new cql query
- https://issues.folio.org/browse/UIDATIMP-1202
https://user-images.githubusercontent.com/89512426/176211502-e8f2902b-6eaf-4b4d-95d9-1357a7ba06fe.mp4
> UIDATIMP-1202:Improve cql query to get job profiles for further import processing

- CHANGELOG.md
- package.json
- src/redux/actions/ActionCreator.js
- src/redux/reducers/Reducer.js
- src/settings/DataImportSettings/DataImportSettings.js
- src/settings/JobProfiles/JobProfilesForm.js
- src/settings/JobProfiles/tests/ViewJobProfile.test.js
- test/jest/__mock__/stripesCore.mock.js
https://issues.folio.org/browse/UIDATIMP-1203
> Release v5.1.6

- CHANGELOG.md
- src/components/OverrideProtectedFieldsTable/OverrideProtectedFieldsTable.js
- src/settings/MappingProfiles/ViewMappingProfile.js
- src/settings/MappingProfiles/detailsSections/edit/MappingMARCAuthorityDetails.js
- src/settings/MappingProfiles/detailsSections/view/MappingMARCAuthorityDetails.js
- src/settings/MappingProfiles/detailsSections/view/index.js
- src/settings/MappingProfiles/detailsSections/view/tests/MappingMARCAuthorityDetails.test.js
- src/utils/constants.js
* As a staff person viewing a field mapping profile for MARC Authority Updates, I want to see clearer indication the field protections can be applied, but cannot be overridden
* Created `<MappingMARCAuthorityDetails />` component to display field mapping profile for MARC Authority Updates
* Covered `<MappingMARCAuthorityDetails />` component with tests
* Added prop `isViewMode` to `<OverrideProtectedFieldsTable />` component to hide subtitle in view mode
[UIDATIMP-1248](https://issues.folio.org/browse/UIDATIMP-1248)
https://user-images.githubusercontent.com/85172747/195563111-2d15aed3-82a3-4b08-8542-711b4616fc57.mp4
> UIDATIMP-1248: Update the field mapping profile for MARC Authority Updates - View screen

- CHANGELOG.md
- src/routes/ViewAllLogs/ViewAllLogsFilters.js
It's needed to filter by a keyword or text string contained in the User or Job profile filter, rather than a keyword or text string that begins the User or Job profile filter
- Provide `onFilter` prop to `Selection` component with Regex to filter options
https://issues.folio.org/browse/UIDATIMP-1254
**Before**
**After**
> UIDATIMP-1254: Change the View all User/Job profile filter searches from Begins to Contains

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceLineInformation.js
* Remove the error appearing when switching between record types on the field mapping profile form
* Added optional chaining for `releaseEncumbranceCheckbox` variable
[UIDATIMP-1250](https://issues.folio.org/browse/UIDATIMP-1250)
https://user-images.githubusercontent.com/85172747/196391651-a48a57d2-b707-4caa-a0fc-7f441f4415f5.mp4
> UIDATIMP-1250: Error during switching between record types on field mapping profile form

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/ExtendedInformation.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceAdjustments.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceLineAdjustments.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceLineInformation.js
> UIDATIMP-1250:  Error during switching between record types on field mapping profile form

- CHANGELOG.md
- src/components/FieldOrganization/FieldOrganization.js
Vendor name lookup is hidden when the field is disabled but the field is required so it's unable to save the profile
- Show `Organization look-up` even if the text field is disabled, otherwise, I do not see the need to use this component at all, you can simply render the disabled text field
- Add possibility to clear the field value even if the field is disabled
https://issues.folio.org/browse/UIDATIMP-1290
> UIDATIMP-1290: Invoice field mapping profile: Vendor name lookup is hidden

- CHANGELOG.md
- src/settings/ActionProfiles/ViewActionProfile/ViewActionProfile.js
- src/settings/ActionProfiles/ViewActionProfile/ViewActionProfile.test.js
- src/settings/JobProfiles/ViewJobProfile/ViewJobProfile.js
- src/settings/JobProfiles/tests/ViewJobProfile.test.js
- src/settings/MappingProfiles/ViewMappingProfile/ViewMappingProfile.js
- src/settings/MappingProfiles/tests/ViewMappingProfile.test.js
- src/settings/MatchProfiles/ViewMatchProfile/ViewMatchProfile.js
- src/settings/MatchProfiles/ViewMatchProfile/ViewMatchProfile.test.js
* After duplicating profiles duplicated view details information is displayed
* Renamed the resource name in `manifest` for all the view forms
[UIDATIMP-1285](https://issues.folio.org/browse/UIDATIMP-1285)
https://user-images.githubusercontent.com/85172747/201671432-3c8f0826-0955-4cb3-ba4f-c485c167426f.mp4
> UIDATIMP-1285: After duplicating profiles the previous view details information is displayed

- CHANGELOG.md
- src/settings/MappingProfiles/EditMappingProfile/EditMappingProfile.js
* After clicking Edit button on existed field mapping profile, the header of the page is "New mapping profile" instead of "Edit"
* Added `layerType` prop to `MappingProfilesForm` component to detect type of the layer and display the correct header
[UIDATIMP-1302](https://issues.folio.org/browse/UIDATIMP-1302)
https://user-images.githubusercontent.com/85172747/201655747-c3c28d30-90dc-4391-bf3c-d5efd74d1cf9.mp4
> UIDATIMP-1302: Incorrect name of the page in Edit mode of field mapping profile

- CHANGELOG.md
- src/settings/ActionProfiles/ViewActionProfile/ViewActionProfile.js
- src/settings/ActionProfiles/ViewActionProfile/ViewActionProfile.test.js
- src/settings/JobProfiles/ViewJobProfile/ViewJobProfile.js
- src/settings/JobProfiles/tests/ViewJobProfile.test.js
- src/settings/MappingProfiles/ViewMappingProfile/ViewMappingProfile.js
- src/settings/MappingProfiles/tests/ViewMappingProfile.test.js
- src/settings/MatchProfiles/ViewMatchProfile/ViewMatchProfile.js
- src/settings/MatchProfiles/ViewMatchProfile/ViewMatchProfile.test.js
> UIDATIMP-1285: After duplicating profiles the previous view details information is displayed (master)

- CHANGELOG.md
- src/settings/MappingProfiles/EditMappingProfile/EditMappingProfile.js
> UIDATIMP-1302: Incorrect name of the page in Edit mode of field mapping profile (master)

- CHANGELOG.md
- src/components/DetailsKeyShortcutsWrapper/DetailsKeyShortcutsWrapper.js
- src/components/SearchAndSort/SearchAndSort.js
- src/settings/ActionProfiles/ViewActionProfile/ViewActionProfile.js
- src/settings/FileExtensions/ViewFileExtension/ViewFileExtension.js
- src/settings/JobProfiles/ViewJobProfile/ViewJobProfile.js
- src/settings/MappingProfiles/ViewMappingProfile/ViewMappingProfile.js
- src/settings/MatchProfiles/ViewMatchProfile/ViewMatchProfile.js
- src/utils/constants.js
- src/utils/craftLayerURL.js
- src/utils/tests/craftLayerURL.test.js
* Enable using shortcuts for creating, editing and duplicating profiles
* When we try to create new profile, basic path is splitted by `/`, cut first four elements (`'', 'settings', 'data-import', 'profileType'`) and push the layer type `create` and return joined path with search query (`/settings/data-import/profileType/create?sort=name`)
* When we try to edit or duplicate profile, basic path is splitted by `/` (`'', 'settings', 'data-import', 'profileType', 'view', 'profileId'`) we look for the view layer and replace it with edit or duplicate, return joined path with search query (`/settings/data-import/profileType/edit/profileId?sort=name`)
[UIDATIMP-1300](https://issues.folio.org/browse/UIDATIMP-1300)
https://user-images.githubusercontent.com/85172747/201654183-a1dcb1d1-1a74-40af-8c97- …
> UIDATIMP-1300: Data import settings: Shortcuts for creating, editing and duplicating don't work

- CHANGELOG.md
- src/utils/getIdentifierTypes.js
- src/utils/tests/getIdentifierTypes.test.js
An error message appears after the user tries to create a new match profile or edit/duplicate existing
- Remove the extra slash to fix the request URL
- Fix tests
https://issues.folio.org/browse/UIDATIMP-1319
> UIDATIMP-1319: Error in module after creating new match profile

- CHANGELOG.md
- src/settings/JobProfiles/ViewJobProfile/ViewJobProfile.js
- src/settings/JobProfiles/tests/ViewJobProfile.test.js
Reverts folio-org/ui-data-import#1285
> Revert "UIDATIMP-1299: 'Completed with errors' after double clicking run import (b5.3)"

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/tests/MappingOrderDetails.test.js
- src/settings/MappingProfiles/detailsSections/view/tests/MappingOrderDetails.test.js
To cover Order field mapping profile with unit tests
- Add unit tests for the mapping order details view/edit components
https://issues.folio.org/browse/UIDATIMP-1291
> UIDATIMP-1291: Cover Order field mapping profile with unit tests

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/OrderInformation.js
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/tests/OrderInformation.test.js
- src/settings/MappingProfiles/initialDetails/ORDER.js
To ensure that the default value for Purchase order lines limit setting displays in the Order field mapping profile
- Add a value to the initial field value
- Assign a value set in settings if exists
https://issues.folio.org/browse/UIDATIMP-1337
> UIDATIMP-1337: Order field mapping profile: Include default value for PO line limit setting

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/OrderInformation.js
* Remove "Something went wrong" error message after `Order` record type selection on field mapping profile 
* Removed dependencies to prevent rerendering in `useEffect` hook in `OrderInformation` component
*  Cover `purchaseOrderLinesLimitValue` with `useMemo` hook
[UIDATIMP-1344](https://issues.folio.org/browse/UIDATIMP-1344)
https://user-images.githubusercontent.com/85172747/211541295-55dd2817-feba-430f-8fe0-1583b9b8e5f1.mp4
> UIDATIMP-1344: Error after selecting order option on field mapping profile

- src/settings/MappingProfiles/detailsSections/constants.js
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/ItemDetails.js
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/Vendor.js
UPDATES after re-checking via new improvements from UI.
- Set "repeatableFieldAction": "EXTEND_EXISTING" for `contributors` and `refNumbers` fields.
- Adjust sending values for "Create Inventory" fields.
https://issues.folio.org/browse/UIDATIMP-1333
> UIDATIMP-1333: Improve mapping profile for Orders (follow-up)

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/utils.js
* Remove error "Something went wrong" when switching order option on field mapping profile edit screen 
* Added optional chaining in `getFieldValueFromDetails`, `getBoolFieldValueFromDetails`, `transformSubfieldsData` and `getFieldValue` to prevent errors appearing
[UIDATIMP-1346](https://issues.folio.org/browse/UIDATIMP-1346)
https://user-images.githubusercontent.com/85172747/212067403-50719507-72b5-4dd9-a4a8-257a37ce45eb.mp4
> UIDATIMP-1346: Add optional chaining to prevent errors appearing when switching between record types

- CHANGELOG.md
- src/components/DataFetcher/DataFetcher.js
- src/utils/constants.js
* To ensure that Inventory Single Record Import jobs do not display on the Data Import landing page, but only on the View all page
* Added `fileNameNotAny` parameter to query. It allows us to fetch `jobExecutions` without `fileName=No file name`
* Created constant `NO_FILE_NAME`
[UIDATIMP-1314](https://issues.folio.org/browse/UIDATIMP-1314)
https://user-images.githubusercontent.com/85172747/213471076-8fc3a116-39bb-4ee7-ab84-67c0eef71147.mp4
> UIDATIMP-1314: Add fileNameNotAny parameter to query to Suppress ISRI imports from the Data Import landing page

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/view/MappingOrderDetails.js
- src/settings/MappingProfiles/detailsSections/view/OrderDetailsSection/ItemDetails.js
- src/settings/MappingProfiles/detailsSections/view/OrderDetailsSection/PhysicalResourceDetails.js
- src/settings/MappingProfiles/detailsSections/view/OrderDetailsSection/Vendor.js
- src/settings/MappingProfiles/detailsSections/view/OrderDetailsSection/index.js
To fix accessibility issues on the Data Import Field mapping Orders View screen
- Fix ids to be unique
- Create separate tickets to fix remaining stripes a11y issues - [STSMACOM-728](https://issues.folio.org/browse/STSMACOM-728), [STCOM-1074](https://issues.folio.org/browse/STCOM-1074)
https://issues.folio.org/browse/UIDATIMP-1332
> UIDATIMP-1332: Accessibility errors: Data Import Field mapping Orders View screen

- CHANGELOG.md
- src/routes/ViewJobLog.js
- src/routes/tests/ViewJobLog.test.js
After user import file and try to navigate to the JSON tab "Something went wrong" error message appears.
- BE schema has been updated which caused an error on UI. Update the `relatedPoLineInfo` field name.
https://issues.folio.org/browse/UIDATIMP-1363
> UIDATIMP-1363: "Something went wrong" error message appears after trying to reach JSON tab

- CHANGELOG.md
- src/components/AcceptedValuesField/AcceptedValuesField.js
- src/settings/MappingProfiles/detailsSections/constants.js
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/ItemDetails.js
The dropdown list of values for Product Identifier Types in the Order field mapping profile shows the entire list of Inventory Identifier types. It should show only a subset of those types.
- Add a new optional prop to the `AcceptedValuesField` component to format options
- Filter list options by name
- Sort `AcceptedValuesField` props in alphabetical order
https://issues.folio.org/browse/UIDATIMP-1362
> UIDATIMP-1362: Order field mapping profile: Update the list of product identifier types

- src/settings/MappingProfiles/detailsSections/constants.js
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/OrderInformation.js
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/tests/OrderInformation.test.js
The poLinesLimit field displays the default value instead of the value fetched from the Order/Settings. That is because of a sequence of redux-form change actions applied.
- Send the request to fetch poLinesLimit and change the form field value after the component renders.
> UIDATIMP-1348: Create/Edit - Display poLinesLimit value from the Order/Settings instead of default (follow-up)

- CHANGELOG.md
- src/routes/JobSummary/components/RecordsTable.js
* To provide a summary for Orders created via Data Import
* Replaced `orderActionStatus` with `poLineActionStatus`
[UIDATIMP-1264](https://issues.folio.org/browse/UIDATIMP-1264)
https://user-images.githubusercontent.com/85172747/216570981-7bea58b5-b744-45bf-9793-655ab26f1187.mp4
> UIDATIMP-1264: Create the UI for the Orders Log info in the DI job log

- CHANGELOG.md
- src/components/UploadingJobsDisplay/UploadingJobsDisplay.js
- src/utils/fetchJsonShemas.js
leverage cookie-based authentication in all API requests, removing the request header x-okapi-token and adding the request option credentials: "include" in all FOLIO API requests.
https://issues.folio.org/browse/UIDATIMP-1338
> UIDATIMP-1338: leverage cookie-based authentication in all API requests

- CHANGELOG.md
- package.json
* Add the following permission: **Organizations: View**
* Added `organizations.organizations.collection.get` to `package.json`
[UIDATIMP-1375](https://issues.folio.org/browse/UIDATIMP-1375)
> UIDATIMP-1375: Adjust UI permission for DI Settings

- CHANGELOG.md
- src/settings/MatchProfiles/MatchProfiles.js
- src/utils/constants.js
* Remove loading `note.json` schema that doesn't exist
[UIDATIMP-1339](https://issues.folio.org/browse/UIDATIMP-1339)
https://user-images.githubusercontent.com/85172747/218074038-b5510391-73ce-42a1-b135-24cea4cdfcc5.mp4
> UIDATIMP-1339: Remove fetching note.json

- CHANGELOG.md
- package.json
* In the UI permission: **Data import: Can upload files, import, and view logs** add the following permission: **Orders: Can view Orders and Order lines**
* Added `ui-orders.orders.view` to `package.json`
[UIDATIMP-1376](https://issues.folio.org/browse/UIDATIMP-1376)
> UIDATIMP-1376: Add permission for viewing Order and Order lines on JSON tab in DI Settings

- CHANGELOG.md
- src/components/ProfileAssociator/AssociatorEditable.js
- src/settings/MappingProfiles/tests/MappingProfilesForm.test.js
When removing an action profile from a field mapping profile, if one of multiple action profiles is removed, an error displays during the Save process
- Generate the correct payload to be sent to BE
- Add unit tests
https://issues.folio.org/browse/UIDATIMP-1350
> UIDATIMP-1350: Error when saving a field mapping profile with some (not all) of related action profiles unlinked

- CHANGELOG.md
- src/components/SearchAndSort/SearchAndSort.js
Data import profiles do not always display in alphabetical order. Sorting reset when closing the view details screen.
- Set default sort when navigating back to the result list
https://issues.folio.org/browse/UIDATIMP-1330
> UIDATIMP-1330: Data Import profiles not in alpha order

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/constants.js
BE expects the value as Receipt Not Required (uppercase capital letters). Change the accepted values list from "Receipt not required" to "Receipt Not Required"
- Change the field value from "Receipt not required" to "Receipt Not Required"
https://issues.folio.org/browse/UIDATIMP-1389
> UIDATIMP-1389: Order import: creating an order with Receipt not required causes an error

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/constants.js
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/POLineDetails.js
- translations/ui-data-import/en.json
For the Order field mapping profile's Payment status field, the wrong values are showing in the dropdown list.
- Fix Payment not required dropdown option
https://issues.folio.org/browse/UIDATIMP-1386
> UIDATIMP-1386: Order field mapping profile: Fix the values in the Payment status field

- CHANGELOG.md
- src/components/FieldOrganization/FieldOrganization.js
- src/settings/MappingProfiles/detailsSections/edit/MappingOrderDetails.js
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/EResourcesDetails.js
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/PhysicalResourceDetails.js
- src/settings/MappingProfiles/detailsSections/hooks/useOrganizationValue.js
- src/settings/MappingProfiles/detailsSections/utils.js
* Add ability to clear manually of the Vendor/Material supplier/Access provider fields
* Change the `redux-form` when user tries to clear the Vendor/Material supplier/Access provider fields
[UIDATIMP-1388](https://issues.folio.org/browse/UIDATIMP-1388)
https://user-images.githubusercontent.com/85172747/221903756-10540ba2-0240-420f-9876-5bf7eed8c290.mp4
> UIDATIMP-1388: Add ability to clear manually of the Vendor/Material supplier/Access provider fields

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/EResourcesDetails.js
- translations/ui-data-import/en.json
* Adjust the information icon for the E-resources Create inventory field to make it clearer
* Updated translation for `en.json`
[UIDATIMP-1399](https://issues.folio.org/browse/UIDATIMP-1399)
> UIDATIMP-1399: Adjust text for info icon for E-resources Create inventory field

- CHANGELOG.md
- src/components/FieldOrganization/FieldOrganization.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/VendorInformation.js
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/PhysicalResourceDetails.js
* Allow to select organization with disabled text field
* Added `isPluginDisabled` prop to disable `Organization look-up`
[UIDATIMP-1416](https://issues.folio.org/browse/UIDATIMP-1416)
https://user-images.githubusercontent.com/85172747/227503823-6faff1e9-7c73-493b-b0cf-46cbfbc36c9a.mp4
> UIDATIMP-1416: Disable field and lookup separately in the "Organization look-up"

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/EResourcesDetails.js
- src/settings/MappingProfiles/detailsSections/utils.js
Cannot save the profile when switching between Order formats (selecting Physical Resource value), Server communication problem error appears.
- The issue was because of setting `''` instead of `ALL_FALSE` initial value to the `booleanActionField`, fixed that
https://issues.folio.org/browse/UIDATIMP-1419
> UIDATIMP-1419: Order field mapping profile: Cannot save the profile when switching between Order formats

- CHANGELOG.md
- src/components/JobLogsContainer/JobLogsContainer.js
- src/routes/Home.js
- src/routes/ViewAllLogs/ViewAllLogs.js
- src/settings/JobProfiles/ViewJobProfile/ViewJobProfile.js
- src/settings/JobProfiles/tests/ViewJobProfile.test.js
- src/utils/fileNameCellFormatter.js
- src/utils/index.js
- src/utils/tests/fileNameCellFormatter.test.js
To provide easy navigation from a job profile to recent imports that used the profile
- Create `fileNameCellFormatter` util to render fileName as a hotlink and use it in different places
- Add unit tests
https://issues.folio.org/browse/UIDATIMP-1356
> UIDATIMP-1356: Create hotlink from file name in job profile detail view to job log details

- CHANGELOG.md
- src/components/JobLogsContainer/JobLogsContainer.js
- src/utils/index.js
- src/utils/jobProfileNameCellFormatter.js
- src/utils/tests/jobProfileNameCellFormatter.test.js
To change the job profile name in the log summary into a hotlink.
- Create `jobProfileNameCellFormatter` util to render a job profile name as a link
- Cover it with unit tests
https://issues.folio.org/browse/UIDATIMP-1355
> UIDATIMP-1355: Landing page: Create hotlink from job profile name in log to the job profile details

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/tests/MappingHoldingsDetails.test.js
- src/settings/MappingProfiles/detailsSections/edit/tests/MappingInstanceDetails.test.js
- src/settings/MappingProfiles/detailsSections/edit/tests/MappingInvoiceDetails.test.js
- src/settings/MappingProfiles/detailsSections/edit/tests/MappingItemDetails.test.js
- src/settings/MappingProfiles/detailsSections/edit/tests/MappingOrderDetails.test.js
- src/settings/MappingProfiles/tests/MappingProfilesForm.test.js
- src/settings/MatchProfiles/MatchProfiles.test.js
[UIDATIMP-1436](https://issues.folio.org/browse/UIDATIMP-1436)
> UIDATIMP-1436: Fix eslint errors

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceInformation.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/tests/InvoiceInformation.test.js
- translations/ui-data-import/en.json
Importer cannot create an order or invoice for a designated acquisitions unit unless the user is a member of that acquisitions unit. This story adds an info icon to the Invoice field mapping profile to make that more clear
- Render info icon next to acq units field
- Add unit tests
https://issues.folio.org/browse/UIDATIMP-1427
> UIDATIMP-1427: Invoice field mapping: Add info icon to the Acq unit field

- CHANGELOG.md
- src/components/SearchAndSort/SearchAndSort.js
- src/settings/ActionProfiles/ActionProfiles.js
- src/settings/JobProfiles/JobProfiles.js
- src/settings/MappingProfiles/MappingProfiles.js
- src/settings/MatchProfiles/MatchProfiles.js
* If there is a search in the profile settings search box, delete it if the user changes to a different type of profile
* When component is mounted set `query: ''` in addition to sort
* Set default width 430px for `name` column because it shrinks when switch between profiles
[UIDATIMP-1461](https://issues.folio.org/browse/UIDATIMP-1461)
> UIDATIMP-1461: Clear search field when switching between profile types

- CHANGELOG.md
- src/settings/MappingProfiles/initialDetails/HOLDINGS.js
- src/settings/MappingProfiles/initialDetails/ITEM.js
To avoid hardcoding uri as required in di-core use the new "required" field on UI in mapping rule for uri.
Prevent creating empty notes.
- Add `required` prop to initial values of mentioned subfields.
https://issues.folio.org/browse/UIDATIMP-1384
> UIDATIMP-1384: Provide "required" field for notes and electronic access subfields in field mapping

- CHANGELOG.md
- package.json
Bump the major versions of optionalDependencies so they align with peer-dependency versions.
https://issues.folio.org/browse/UIDATIMP-1532
> UIDATIMP-1532: Bump the major versions of @folio/plugin-find-organization optionalDependencies

- CHANGELOG.md
- src/settings/MappingProfiles/MappingProfilesForm.js
- src/settings/MappingProfiles/tests/MappingProfilesForm.test.js
* For the first release of ECS: Holdings, Items, MARC Holdings, Orders, and Invoices are not included in the Central tenant. They will only be available for the member tenants. This story suppresses field mapping options for record types that are not included in the Central tenant
* Check is user is in central tenant and pick folio record types.
* Added unit tests.
[UIDATIMP-1553](https://issues.folio.org/browse/UIDATIMP-1553)
###Central tenant
> UIDATIMP-1553: Adjust the record options in Central tenant field mapping profiles

- CHANGELOG.md
- src/routes/JobSummary/components/RecordsTable.js
* When you want to create an item connected to an existing holdings, you match to that holdings hrid and have an action to create item. If you try to create it Item will be created and log form item empty.
* If holdings information is empty, display only item information
[UIDATIMP-1564](https://issues.folio.org/browse/UIDATIMP-1564)
https://github.com/folio-org/ui-data-import/assets/85172747/beea1021-5df3-41a0-b7b3-a9bc32736f45
> UIDATIMP-1564: Display item information without holdings

- CHANGELOG.md
- src/components/ListView/ListView.js
- src/settings/ActionProfiles/ActionProfiles.js
* Hide the action profile checkboxes and the checkbox actions in the Data Import Action profile settings, until a user can actually do something with them.
* Removed unused items from `actionMenuItems`.
* Removed unused `selected` option from `visibleColumns`.
* Removed `@connect(mapStateToProps)` and `@withCheckboxList()` since there is no checkbox column.
* Updated `setList` method in `ListView` component in order to avoid error messages in components which use `withCheckboxList`
[UIDATIMP-1497](https://issues.folio.org/browse/UIDATIMP-1497)
https://github.com/folio-org/ui-data-import/assets/85172747/4512b323-a8c6-43c5-982f-3c1fe607067f
> UIDATIMP-1497: Action profile Settings: suppress checkboxes and checkbox actions

- CHANGELOG.md
- src/settings/MappingProfiles/MappingProfiles.js
- src/settings/MappingProfiles/tests/MappingProfiles.test.js
* Hide the field mapping profile checkboxes and the checkbox actions in the Data Import Field mapping profile settings, until a user can actually do something with them.
* Removed unused items from `actionMenuItems`.
* Removed unused selected option from `visibleColumns`.
* Removed `@connect(mapStateToProps)` and `@withCheckboxList()` since there is no checkbox column.
* Updated unit tests.
[UIDATIMP-1498](https://issues.folio.org/browse/UIDATIMP-1498)
> UIDATIMP-1498: Field mapping profile Settings: suppress checkboxes and checkbox actions

- CHANGELOG.md
- src/settings/JobProfiles/JobProfiles.js
- src/settings/JobProfiles/tests/JobProfiles.test.js
* Hide the job profile checkboxes and the checkbox actions in the Data Import Job profile settings, until a user can actually do something with them.
* Removed unused items from `actionMenuItems`.
* Removed unused selected option from `visibleColumns`.
* Removed `@connect(mapStateToProps)` and `@withCheckboxList()` since there is no checkbox column.
* Updated unit tests.
[UIDATIMP-1495](https://issues.folio.org/browse/UIDATIMP-1495)
> UIDATIMP-1495: Job profile Settings: suppress checkboxes and checkbox actions

- CHANGELOG.md
- src/settings/JobProfiles/JobProfilesForm.js
Fetching profiles associations is not handled properly that causes page crash if some error occurred.
- Handle errors
> UIDATIMP-1572: When error occurs during saving edited job profile page crashes

- CHANGELOG.md
- src/routes/JobSummary/components/RecordsTable.js
- src/routes/JobSummary/components/utils.js
* Display error when there is an error message
* Added additional check whether there is an error message
[UIDATIMP-1573](https://issues.folio.org/browse/UIDATIMP-1573)
> UIDATIMP-1573: Display error when status is discarded and there is an error message

- CHANGELOG.md
- src/settings/MARCFieldProtection/MARCFieldProtection.test.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/ExtendedInformation.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/VendorInformation.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/tests/InvoiceLineAdjustments.test.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/tests/InvoiceLineInformation.test.js
- src/settings/MappingProfiles/detailsSections/edit/MappingInvoiceDetails.js
- src/settings/MappingProfiles/initialDetails/INVOICE.js
Account number does not appear in the imported invoice when account level accounting code is specified for invoice mapping.
- Set `invoice.accountNo` when selecting `Account code` field
https://issues.folio.org/browse/UIDATIMP-1584
> UIDATIMP-1584: Provide "accountNo" field mapping when account-level accounting code is specified for invoice mapping

- CHANGELOG.md
- src/components/ProfileTree/ProfileBranch.test.js
- src/components/ProfileTree/ProfileTree.test.js
- src/components/RecordTypesSelect/RecordTypesSelect.test.js
- src/components/TreeLine/TreeLine.test.js
- test/jest/__mock__/index.js
- test/jest/__mock__/resizeObserver.mock.js
[UIDATIMP-1586](https://issues.folio.org/browse/UIDATIMP-1586)
> UIDATIMP-1586: Mock ResizeObserver to fix failed tests

- CHANGELOG.md
- src/routes/JobSummary/components/RecordsTable.js
- src/routes/JobSummary/components/RecordsTable.test.js
When there is any error related to an instance/authority/orders/invoice, the error column does not display it.
- Check if there is an error in any entity
https://issues.folio.org/browse/UIDATIMP-1590
> UIDATIMP-1590: Job summary: error column does not display errors

- CHANGELOG.md
- src/utils/checkboxList.js
Checkboxes are not cleared after relogin.
- Add `useEffect` with the cleanup function to reset the checkboxes state when the component is unmounted
https://folio-org.atlassian.net/browse/UIDATIMP-1593
https://github.com/folio-org/ui-data-import/assets/55138456/6e10897c-af08-4089-bccf-dd53fac1ae9a
> UIDATIMP-1593: Reset checkboxes state after navigating away from the Home/View all logs page

- CHANGELOG.md
- src/components/LogViewer/LogViewer.css
* Move group of buttons under the title in order to make everything fit on smaller screens (discussed with PO)
* Added `flex-direction: column` style for the toolbar
[UIDATIMP-1594](https://folio-org.atlassian.net/browse/UIDATIMP-1594)
https://github.com/folio-org/ui-data-import/assets/85172747/cf941547-44ec-4ac4-b81a-656f38b3730c
> UIDATIMP-1594: Update style for group of buttons when view data import logs

- CHANGELOG.md
- src/settings/ActionProfiles/ActionProfilesForm.js
- src/settings/ActionProfiles/ActionProfilesForm.test.js
- translations/ui-data-import/en.json
* Since there is no scenario in which a FOLIO user should use a Data Import job to CREATE a MARC Bib without a corresponding Instance, we should update the Action Profile settings.
* Omit `MARC Bibliographic` option when `Create` action is selected.
* Update translation.
* Update unit tests.
[UIDATIMP-1598](https://folio-org.atlassian.net/browse/UIDATIMP-1598)
https://github.com/folio-org/ui-data-import/assets/85172747/b08e77cb-9e12-45d7-be16-efed52080145
> UIDATIMP-1598: Remove MARC Bib option when `Action = Create` and update translation for `Create` option

- CHANGELOG.md
- package.json
Add missed “metadata-provider.incomingrecords.get” permission to "ui-data-import.manage" and "ui-data-import.view" permission sets.
- Add missed permission to get incoming records.
https://folio-org.atlassian.net/browse/UIDATIMP-1609
> UIDATIMP-1609: Add permissions to data-import set to get incoming records

- CHANGELOG.md
- src/settings/ActionProfiles/ActionProfiles.js
- src/settings/FileExtensions/FileExtensions.js
- src/settings/JobProfiles/JobProfiles.js
- src/settings/MappingProfiles/MappingProfiles.js
- src/settings/MatchProfiles/MatchProfiles.js
* Currently sorting is performed by first name on the BE side. First name is not always present in the user's information. This causes inconsistent sorting.
* Change order of sorting in profiles' manifest
[UIDATIMP-1613](https://folio-org.atlassian.net/browse/UIDATIMP-1613)
https://github.com/folio-org/ui-data-import/assets/85172747/fd29c105-56f4-4ce5-8f1a-dc8e567d5e2d
https://github.com/folio-org/ui-data-import/assets/85172747/bb83abd4-b34b-43f1-9dc6-c2273785da56
> UIDATIMP-1613: Perform sorting by last name first, instead of first name in `Updated by` column

- CHANGELOG.md
- src/settings/JobProfiles/JobProfilesForm.js
Changes made during duplication of "Default - Create SRS MARC Authority" job profile are not saved and affect original job profile.
- If the layer type is `Duplicate` then put `null` to the `masterWrapperId` field instead of copying the id from the original job profile.
https://folio-org.atlassian.net/browse/UIDATIMP-1622
> UIDATIMP-1622: Changes made during duplication of "Default - Create SRS MARC Authority" job profile are not saved and affect original job profile

- CHANGELOG.md
- package.json
* Update `CHANGELOG.md` for releases `v7.1.7`, `v7.1.8`, `v7.0.7`
* Update `package.json` version for `v7.1.8`
> Update CHAGELOG.md in master branch after releases

- CHANGELOG.md
- src/components/ViewContainer/ViewContainer.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceLineFundDistribution.js
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/CostDetails.js
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/FundDistribution.js
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/tests/FundDistribution.test.js
- src/settings/MappingProfiles/detailsSections/utils.js
- src/settings/MappingProfiles/initialDetails/INVOICE.js
- src/settings/MappingProfiles/initialDetails/ORDER.js
To ensure invoice line mapping when fund distributions field mapping is set explicitly in the invoice mapping profile.
- Wrap the `distributionType` field for Orders and Invoices in quotation marks.
https://folio-org.atlassian.net/browse/UIDATIMP-1644
> UIDATIMP-1644: Wrap value for "distributionType" field mapping with quotation marks

- CHANGELOG.md
- src/utils/formValidators.js
When a user creates a new invoice field mapping profile, saves it and then navigates to the edit form, the page crashes.
- Add default array value to args.
https://folio-org.atlassian.net/browse/UIDATIMP-1646
> UIDATIMP-1646: When navigating to the Invoice field mapping profile edit form the page crashes

- CHANGELOG.md
- src/routes/ViewAllLogs/ViewAllLogs.js
* When user go to completed job with more than 100 records from “View all logs” page and switch the page to the next, and after this go back to “View all logs” page he’ll see that page switched too.
* Reset offset when after first render of `ViewAllLogs` component.
[UIDATIMP-1645](https://folio-org.atlassian.net/browse/UIDATIMP-1645)
> UIDATIMP-1645: Reset offset when open VievAllLogs page

- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/DonorInformation.js
- src/settings/MappingProfiles/initialDetails/ORDER.js
Follow-up PR.
It is needed to fill in the repeatable action field only when adding donors, otherwise, it should be null.
- Handle repeatable action field on donors add/remove.
https://folio-org.atlassian.net/browse/UIDATIMP-1656
> UIDATIMP-1656: Handle donors repeatable action field on add/remove (follow-up)

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceAdjustments.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceLineAdjustments.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/tests/InvoiceAdjustments.test.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/tests/InvoiceLineAdjustments.test.js
- src/settings/MappingProfiles/detailsSections/utils.js
- src/settings/MappingProfiles/initialDetails/INVOICE.js
* Adjust the value for invoice and invoice lines adjustments type field mapping (mapping entries with property "path" = "invoice.adjustments[].type" and "path" = "invoice.invoiceLines[].adjustments[].type"):
- capitalize the first letter of the value 
- wrap the value with escaped quotes 
* When this PR is merged we'll receive the data form BE in format `'\"Amount\"'` instead of `'amount'`.
* Update version of actions/upload-artifact to v4 due to failed build
* Change the form value when user interacts with `TypeToggle` component
* Updated default schema for invoice field mapping profile.
* Update the behavior of `renderAmountValue` method.
* Added unit tests.
[]()
https://github.com/user-attachments/assets/178ca1a9-ccb3-4157-bc36-ac9786e58922
> UIDATIMP-1662: Adjust value for invoice and invoice lines adjustments "Type" field mapping

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/InstanceDetailsSections/tests/InstanceRelationship.test.js
- src/settings/MappingProfiles/detailsSections/view/tests/MappingInstanceDetails.test.js
- translations/ui-data-import/en.json
It has been requested to change the Instance accordion name ‘Instance relationship (analytics and bound-with) to simply be '*Instance relationship*’.
- Change label ‘Instance relationship (analytics and bound-with)' to '*Instance relationship*’.
https://folio-org.atlassian.net/browse/UIDATIMP-1670
> UIDATIMP-1670: Update 'Instance relationship' accordion name - Data Import Mapping

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/ExtendedInformation.js
The checkbox for “export to accounting” cannot be checked. If you click near “check subscription overlap” the checkbox “export to accounting” is checked but won’t stay checked. So you can also not check the checkbox for “check subscription overlap”.
- Fix checkboxes indexes
https://folio-org.atlassian.net/browse/UIDATIMP-1671
> UIDATIMP-1671: Invoice field mapping profile: cannot check export to accounting checkbox

- CHANGELOG.md
- src/settings/MatchProfiles/MatchProfiles.js
- src/settings/MatchProfiles/MatchProfiles.test.js
* List of all existing record fields should be displayed.
* `!isEqual(prevProps.stripes.discovery.modules, this.props.stripes.discovery.modules` is always `false`. That's why we never fetch JSON schemas.
* Fetch options only once and check if `this.props.stripes.discovery.modules` is not empty in order to avoid failed requests. 
[UIDATIMP-1689](https://folio-org.atlassian.net/browse/UIDATIMP-1689)
> UIDATIMP-1689: Populate `Existing records` field when create match profile

- CHANGELOG.md
- package.json
Quesnelia bugfix
After refactoring the request for getting SRS MARC data necessary permissions were missed.
- Rename "source-storage.records.get" to "source-storage.sourceRecords.get"
https://folio-org.atlassian.net/browse/UIDATIMP-1688
> UIDATIMP-1688: Rename permission after refactoring request for getting SRS MARC data

- CHANGELOG.md
- src/components/ImportJobs/ImportJobs.js
- src/components/ImportJobs/ImportJobs.test.js
* Trigger file selection window to open after click `Choose other files to upload` button
* First, it hides the file extensions modal, then sets a timeout (`setTimeout(() => openDialogWindow(), 0)`) to open the dialog window asynchronously, ensuring that any changes or state updates are completed before the dialog is opened.
[UIDATIMP-1683](https://folio-org.atlassian.net/browse/UIDATIMP-1683)
https://github.com/user-attachments/assets/416a7c1e-f108-4f2c-9698-40913722b64d
> UIDATIMP-1683: Trigger file selection window to open after click `Choose other files to upload` button

- src/components/ListView/ListView.js
- src/components/MatchingFieldsManager/MatchingFieldsManager.js
- src/components/WithTranslation/WithTranslation.js
- src/settings/ActionProfiles/ActionProfiles.js
- src/settings/FileExtensions/ViewFileExtension/ViewFileExtension.js
- src/settings/MappingProfiles/MappingProfiles.js
- src/settings/MatchProfiles/MatchProfiles.js
Just like PR #1681, replace annotations that don't play nice with our esbuild-loader setup. Unfortunately, I missed a bunch of annotations in the original PR.
Refs [UIDATIMP-1712](https://folio-org.atlassian.net/browse/UIDATIMP-1712)
> UIDATIMP-1712 apply wrappers with _.flow()

- CHANGELOG.md
- src/settings/ActionProfiles/ViewActionProfile/ViewActionProfile.js
- src/settings/FileExtensions/FileExtensions.js
- src/settings/FileExtensions/ViewFileExtension/ViewFileExtension.js
- src/settings/JobProfiles/ViewJobProfile/ViewJobProfile.js
- src/settings/MappingProfiles/ViewMappingProfile/ViewMappingProfile.js
- src/settings/MatchProfiles/ViewMatchProfile/ViewMatchProfile.js
The 'Something went wrong' error message is displayed after clicking on existing job/match/action/mapping profiles.
- Place wrappers in right order to not lose any data after migrating to `flow()`.
https://folio-org.atlassian.net/browse/UIDATIMP-1716
> UIDATIMP-1716: Place wrappers in right order to not lose any data after applying `flow()`

- CHANGELOG.md
- src/utils/constants.js
Some 'Existing record field' options are missing in dropdown.
- jsonSchemas changed location/name, because of that some requests failed, I updated them accordingly.
https://folio-org.atlassian.net/browse/UIDATIMP-1736
> UIDATIMP-1736: The 'Existing record field' list does not contain criterion value types in the match profile

- CHANGELOG.md
- package.json
[UIDATIMP-1739](https://folio-org.atlassian.net/browse/UIDATIMP-1739)
> UIDATIMP-1739: Add `optionalOkapiInterfaces` with `inventory-storage` and `organization-storage` interfaces
