folio-org/ui-data-import

- CHANGELOG.md
- package.json
- src/components/Report/Report.js
- src/components/Report/components/RecordItem/RecordItem.js
- src/components/Report/components/RecordPreview/RecordPreview.js
- src/components/ResultPanel/ResultPanel.js
- src/components/SearchPanel/SearchPanel.js
- src/routes/Application.js
- src/settings/general-settings.js
- src/settings/index.js
- src/settings/some-feature-settings.js
This updates `stripes-*` dependencies and their corresponding imports to make use of stripes framework v1.0.0.
> FOLIO-1549 Use stripes-framework v1.0.0

- src/components/ImportJobs/ImportJobs.js
- src/components/UploadingJobsDisplay/UploadingJobsDisplay.js
- src/components/UploadingJobsDisplay/components/FileItem/FileItem.css
- src/components/UploadingJobsDisplay/components/FileItem/FileItem.js
- src/components/UploadingJobsDisplay/components/FileItem/fileItemStatuses.js
- translations/ui-data-import/en.json
To have UI for error handling, when something goes wrong while files are uploading (e.g. timeout, communication problem)
Extend `FileItem` component to support multiple states like `uploading`, `uploaded` and `failed` and differentiate behavior based on that. Additionally, cover both error cases: either error during posting upload definition or error on individual file error.
> UIDATIMP-63: Add UI for file uploading fail.

- CHANGELOG.md
- src/components/UploadingJobsDisplay/UploadingJobsDisplay.js
- src/components/UploadingJobsDisplay/components/FileItem/FileItem.js
- src/components/UploadingJobsDisplay/components/FileItem/fileItemStatuses.js
- src/components/UploadingJobsDisplay/components/FileItem/getFileItemMeta.js
- translations/ui-data-import/en.json
- translations/ui-data-import/en_US.json
Implement deleting failed files from server.
This feature adds new behavior to the **FileItem** component to initiate the removal of the file entry on the backend and display a loading indicator while deleting is in progress. In case of the backend error, the toast shows the error message and loading indicator hides.
Happy path
Unhappy path
> UIDATIMP-72: Implement deleting failed files from server feature

- src/routes/Home.js
It's a consistent pattern across all modules with a results-pane to remove the padding from the pane (since it's applied inside the MultiColumnList anyway).
> Removed padding from results pane

- src/settings/FileExtensions/ViewFileExtension.js
- test/bigtest/tests/new-file-extensions-test.js
Add changes, requested by Ann-Marie and Filip
Remove edit icon, show file type with blocked import, handle multiple data types.
> UIDATIMP-61: Remove edit icon, show file type with blocked import, handle multiple data types

- src/components/FileExtensionForm/FileExtensionForm.js
- src/routes/Results.js
We updated stripes-components with an IconButton component that's made specifically for PaneHeaders.
In this PR I replaced the existing IconButton's inside PaneHeaders with the new PaneHeaderIconButton component.
> Replace <IconButton> with <PaneHeaderIconButton>

- src/components/SearchAndSort/SearchAndSort.js
When duplicating a job profile and changing only data type, an human unreadable error message appears in the [story](https://issues.folio.org/browse/UIDATIMP-134).
> UIDATIMP-134: Fix unreadable error message when duplicating job profile

- package.json
- src/index.js
- src/routes/Home.js
- src/routes/ViewAllLogs/ViewAllLogs.js
- src/routes/ViewAllLogs/ViewAllLogsFilterConfig.js
- src/routes/ViewAllLogs/ViewAllLogsSearchConfig.js
- src/routes/ViewAllLogs/index.js
- test/bigtest/interactors/search-and-sort-pane.js
- test/bigtest/tests/view-all-logs-test.js
In the scope of this story was implemented "view all" log screen:
1. First pane - Search & filter pane (there are no filters and search options in this story);
2. Second pane is similar to Logs pane at the landing page
> UIDATIMP-285: Create "view all" log screen

- CHANGELOG.md
- package.json
- src/settings/MappingProfiles/MappingProfilesForm.js
- src/settings/MappingProfiles/ViewMappingProfile.js
* Add action options to choose jobs screen (UIDATIMP-268)
* Add non-editable mode feature for RecordTypesSelect component (UIDATIMP-323)
* Add match details to the View match profile details pane (UIDATIMP-239)
* Create Match Profiles Form renderer (UIDATIMP-325)
* Increase the width of the View details pane for Match profiles (UIDATIMP-332)
* Create Associator Component (UIDATIMP-275)
* Attach a field mapping profile to an action profile that does not have one (UIDATIMP-269)
* Attach one or more action profiles to a field mapping profile (UIDATIMP-279)
> Release v1.7.0

- CHANGELOG.md
- src/components/ProfileAssociator/AssociatedList.js
- src/components/ProfileTree/ProfileBranch.js
- src/components/ProfileTree/ProfileLabel.js
- src/components/ProfileTree/ProfileLinker/ProfileLinker.js
- src/components/ProfileTree/ProfileTree.js
- src/settings/JobProfiles/JobProfilesForm.js
- src/utils/constants.js
- test/bigtest/mocks/field-mapping-rules-samples.js
- Implement `Profiles` removal from any `<ProfileTree>` node.
- Implement `deletedRelations` pool composition for `PUT` HTTP request
- Validate removed items on whether they are really need to be removed server-side or just removed from tree nodes.
- Implement common `unlink` and `remove` methods inside `<ProfileTree>` component.
- Push those method refs into all the appropriate `<ProfileTree>` children (`<ProfileBranch>` and `<ProfileLabel>`) as props.
[UIDATIMP-315](https://issues.folio.org/browse/UIDATIMP-315)
> UIDATIMP-315: Job profile details, part 4: unlinking match or action profiles :: DONE

- CHANGELOG.md
- src/components/SearchAndSort/SearchAndSort.js
When duplicating matching, action, and field mapping profiles, any linked profiles should be removed.
Omit parent and child profiles when the duplicate form renders.
[UIDATIMP-410](https://issues.folio.org/browse/UIDATIMP-410)
> UIDATIMP-410: Wipe out linked profiles when duplicate a profile

- CHANGELOG.md
- src/settings/MatchProfiles/ViewMatchProfile.js
The existing record field name is showing the backend field name instead of the label.
Get back `getFieldMatched` method for displaying existing record field name correctly
[UIDATIMP-427](https://issues.folio.org/browse/UIDATIMP-427)
> UIDATIMP-427: Fix existing record field name displaying

- CHANGELOG.md
- src/components/RecordTypesSelect/RecordTypesSelect.css
- src/components/RecordTypesSelect/RecordTypesSelect.js
- src/components/RecordTypesSelect/components/CompareRecordSelect.js
- src/components/RecordTypesSelect/components/InitialRecordSelect.js
- src/components/RecordTypesSelect/components/RecordSelect.js
- src/components/TreeLine/TreeLine.js
- src/components/TreeView/TreeView.css
- src/components/TreeView/TreeView.js
Record Type Selection Tree looks broken with RTL locales such as Hebrew and Arabian
Check document.dir and apply appropriate styles
[UIDATIMP-425](https://issues.folio.org/browse/UIDATIMP-425)
> UIDATIMP-425: Fix broken Record Type Selection Tree in RTL mode

- CHANGELOG.md
- src/components/UploadingJobsDisplay/UploadingJobsDisplay.js
- src/settings/JobProfiles/ViewJobProfile.js
- src/utils/loadRecords.js
Remove or set to false `defaultMapping` query param when data-import process is run with chosen JobProfile.
- Add defaultMapping arg to loadRecords method
- Set defaultMapping value false for running process with jobProfile
- Set defaultMapping value true for the default running process
- Put defaultMapping value to the request
[UIDATIMP-418](https://issues.folio.org/browse/UIDATIMP-418)
> UIDATIMP-418: Set defaultMapping query param

- CHANGELOG.md
- src/settings/MappingProfiles/MappingProfilesForm.js
- Mapping Profiles Form existing record type recognition behavior is wrong
- Form loads with empty mapping details section when it loads for existing record edit mode.
- When the user changes existing record type for already existing mapping profile and then returns to original existing record type, form believes nothing has changed and leaves the previous section type initial data that prevents the form from correct work behavior.
- When the form loads with existing record in edit mode it first persists null as previous (initial) existing record type value and then loads the form data with actual value from the form state. This pushes the form logic to believe existing record type has changed and empty initial data load is needed
> UIDATIMP-456 Fix Mapping Profile existing record type recognition behavior :: DONE

- CHANGELOG.md
- src/components/ProfileTree/ProfileBranch.js
- src/components/ProfileTree/ProfileLinker/ProfileLinker.js
- src/components/ProfileTree/ProfileTree.js
- src/settings/JobProfiles/JobProfilesForm.js
- src/utils/fetchProfileSnapshot.js
- test/bigtest/tests/job-profiles/new-job-profiles-test.js
1. When adding to a job profile a match profile with filled "For matches" or "For non-matches" sections, these sections are empty, but when saving the job profile, the linked match profile displays filled sections.
2. When linking some profile to a job profile, then unlinking and save the job profile, unlinked profile are not removed from the tree.
1. Retrieve a profile snapshot with `childSnapshotWrappers` when linking some profile to a job profile.
2. Fill tree data with `childSnapshotWrappers` for an appropriate profile.
3. When linking some match profile to the root match profile, check if this is the same match profile, if not - allow linking, if yes - disallow linking.
4. When unlinking some profile, check if this profile is newly added and if yes - remove this profile from the …
> UIDATIMP-413: Display filled sub-sections of a match profile on linking to a job profile

- CHANGELOG.md
- src/settings/MatchProfiles/MatchProfiles.js
GET request to '_/proxy/tenants/diku/modules' returns 404
Pass correct tenant value to the request
[UIDATIMP-465](https://issues.folio.org/browse/UIDATIMP-465)
> UIDATIMP-465: Fix hardcoded tenant value for the modules retrieving

- CHANGELOG.md
- package.json
* Data Import Field Mapping Profile details: Inventory instance from MARC (UIDATIMP-15)
* Data Import Field Mapping Profile details: Inventory holdings from MARC Bib (UIDATIMP-290)
* Data Import Field Mapping Profile details: Inventory item from MARC Bib (UIDATIMP-292)
* Rearrange the match profile diagram structure (UIDATIMP-411)
* Wipe out lines from the match profile diagram (UIDATIMP-411)
* Provide a profile snapshot with childWrappers when new profile association added to a job profile (UIDATIMP-413)
* Data import settings Match Profiles: Changes for Static value Number, Date submatches (UIDATIMP-414)
* Set defaultMapping query param when data-import process is run with chosen JobProfile to false (UIDATIMP-418)
* Add "profileType" query param to request for get …
> Release v1.8.1

- CHANGELOG.md
- src/components/FlexibleForm/Control.js
- src/settings/MappingProfiles/MappingProfilesForm.js
Repeatable control clones the first row with all of its field names without respect of all the indexes needed.
This happens because Repeatable is designed to work with flat single-level data objects as reference tables row.
> UIDATIMP-443: More than one record cannot be created in Mapping Profiles Form repeatable fields :: FIXED

- CHANGELOG.md
- test/bigtest/mocks/form-config-samples.js
To make clear on the field mapping profile where the mapping details sections end and the Associated action profiles section begins
Configuration for appropriate component has been updated
**Case1**
- Navigate to field mapping profile Create/Edit screen
- Check if line between Associated action profiles section and section above is present
**Case2**
- Navigate to field mapping profile View details screen
- Check if line between Associated action profiles section and section above is present
[UIDATIMP-472](https://issues.folio.org/browse/UIDATIMP-472)
> UIDATIMP 472: Line above associated action profiles has been added

- CHANGELOG.md
- package.json
- src/components/FlexibleForm/Control.js
- src/components/FlexibleForm/ControlDecorators/partials/TextDate.js
- src/components/FlexibleForm/ControlDecorators/withBooleanActions/withBooleanActions.js
- src/components/FlexibleForm/ControlDecorators/withRepeatableActions/withRepeatableActions.js
- src/components/JobLogs/withJobLogsCellsFormatter.js
- src/components/Jobs/components/Job/Job.js
- src/routes/ViewAllLogs/ViewAllLogs.js
- src/settings/ActionProfiles/ActionProfilesForm.js
- src/settings/JobProfiles/ViewJobProfile.js
react-intl no longer uses the legacy `contextTypes` API, so we're back to `injectIntl`.
> UIDATIMP-517 update to react-intl v4

- CHANGELOG.md
- src/components/MARCTable/MARCTable.js
- src/components/MARCTable/MARCTableRow.js
- src/components/MARCTable/MARCTableRowContainer.js
- test/bigtest/interactors/marc-table-interactor.js
- test/bigtest/tests/mapping-profiles/new-mapping-profiles-test.js
To create the up/down arrows that resequence rows in the table of the Field Mapping profile details for MARC modifications
* Add `moveRow` method to the `MARCTable` component
* Add test
[UIDATIMP-496](https://issues.folio.org/browse/UIDATIMP-496)
> UIDATIMP-496: Implement re-order row functionality in the MARCTable

- CHANGELOG.md
- src/components/FlexibleForm/ControlDecorators/withDatePicker/withDatePicker.js
- src/components/FlexibleForm/ControlDecorators/withReferenceValues/withReferenceValues.css
- src/components/FlexibleForm/ControlDecorators/withReferenceValues/withReferenceValues.js
- src/utils/formUtils.js
- test/bigtest/tests/mapping-profiles/mapping-profile-details-test.js
In Instance, Holdings, and Item field mapping profiles, User should only be allowed to select one ref value from the dropdown list. If a second one is selected, it should replace the previously-selected one in the field mapping data field
* Create formatDecoratorValue function in formUtils
* Check incoming value, update it in appropriate way
* Add tests
[UIDATIMP-523](https://issues.folio.org/browse/UIDATIMP-523)
> UIDATIMP-523 Update logic for reference dropdowns with datepicker

- CHANGELOG.md
- src/components/MARCTable/MARCTable.js
- src/components/MARCTable/MARCTableRow.js
- src/components/MARCTable/MARCTableRowContainer.js
- src/settings/MappingProfiles/initialDetails/MARC_BIBLIOGRAPHIC.js
- test/bigtest/interactors/marc-table-interactor.js
- test/bigtest/tests/mapping-profiles/mapping-profile-details-test.js
To create functionality of adding subfields rows main rows in the table of the Field Mapping profile details for MARC modifications
* Add `addSubfieldRow` method to the `MARCTable` component
* Add `removeSubfieldRow` method to the `MARCTable` component
* Add `removeSubfieldRows` method to the `MARCTable` component
* Add `handleActionChange` method to the `MARCTableRow` component
* Add `handleSubActionChange` method to the `MARCTableRow` component
* Add `handleRemoveRow` method to the `MARCTableRow` component
* Add test
[UIDATIMP-488](https://issues.folio.org/browse/UIDATIMP-488)
> UIDATIMP-488: Field Mapping Profile details: MARC Bib from MARC Bib 4 - Add Subsequent line

- CHANGELOG.md
- src/settings/MappingProfiles/initialDetails/HOLDINGS.js
When default value is selected for Holdings type in the Holdings field mapping profile, it does not populate into a newly-created holdings record
[UIDATIMP-542](https://issues.folio.org/browse/UIDATIMP-542)
> UIDATIMP-542 Issue with holdings type field population has been fixed

- CHANGELOG.md
- src/components/FlexibleForm/ControlDecorators/withReferenceValues/withReferenceValues.js
Fix deletion of repeatable fields in Field mapping profiles
[UIDATIMP-538](https://issues.folio.org/browse/UIDATIMP-538)
**Before**
**After**
> UIDATIMP-538: Fix deletion of repeatable fields

- CHANGELOG.md
- package.json
We faced with build failures on Jenkins during npm install step. This is related a new release of react-intl v4.7.1 (released at around 3am EST). To avoid build failures the decision was made to lock previous version of this package.
[UIDATIMP-551](https://issues.folio.org/browse/UIDATIMP-551)
> locking version for react-intl

- CHANGELOG.md
- src/components/ListTemplate/ColumnTemplates/CheckboxColumn.js
- src/components/ListTemplate/HeaderTemplates/CheckboxHeader.js
- src/components/ProfileTree/ProfileLinker/LinkerTrigger.js
- src/components/SearchAndSort/SearchAndSort.js
- src/settings/JobProfiles/JobProfilesForm.js
- src/settings/JobProfiles/ViewJobProfile.js
- test/bigtest/interactors/job-profiles/job-profile-details.js
- test/bigtest/interactors/job-profiles/job-profile-form.js
- test/bigtest/interactors/profile-tree-interactor.js
- translations/ui-data-import/en.json
To fix Accessibility problems for settings/data-import/job-profiles?layer=create page
- add `aria-label` attribute to checkbox in `CheckboxColumn` component
- add `aria-label` attribute to checkbox in `CheckboxHeader` component
- add translations for `aria-label` attributes
- add unique `id` for `Tooltip` in `LinkerTrigger` component
- remove extra `role` attribute for row content in `SearchAndSort`  component
- update tests
[UIDATIMP-433](https://issues.folio.org/browse/UIDATIMP-433)
> UIDATIMP-433: Fix Accessibility problems for settings/data-import/job-profiles?layer=create

- CHANGELOG.md
- src/components/Section/Section.js
Fix rendering qualifier sections in match profiles details with old data.
Add `useEffect` hook to `Section` component to update state if updated `isOpen` prop received.
[UIDATIMP-481](https://issues.folio.org/browse/UIDATIMP-481)
> UIDATIMP-481: Fix rendering qualifier sections with old data

- CHANGELOG.md
- src/components/FlexibleForm/ControlDecorators/withRepeatableActions/withRepeatableActions.js
- src/components/RepeatableActionsField/RepeatableActionsField.js
- src/settings/MappingProfiles/MappingProfilesForm.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/AdministrativeData.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/ElectronicAccess.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/HoldingsDetails.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/HoldingsNotes.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/ReceivingHistory.js
- src/settings/MappingProfiles/detailsSections/edit/InstanceDetailsSections/AdministrativeData.js
- src/settings/MappingProfiles/detailsSections/edit/InstanceDetailsSections/DescriptiveData.js
- src/settings/MappingProfiles/detailsSections/edit/InstanceDetailsSections/InstanceRelationship.js
- src/settings/MappingProfiles/detailsSections/edit/InstanceDetailsSections/TitleData.js
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/AdministrativeData.js
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/ElectronicAccess.js
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/EnumerationData.js
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/ItemNotes.js
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/LoanAndAvailability.js
- src/settings/MappingProfiles/detailsSections/edit/MappingHoldingsDetails.js
- src/settings/MappingProfiles/detailsSections/edit/MappingInstanceDetails.js
- src/settings/MappingProfiles/detailsSections/edit/MappingItemDetails.js
- src/utils/constants.js
- src/utils/formValidators.js
- translations/ui-data-import/en.json
To provide additional validation for repeatable fields on Instance, Holdings, and Item field mapping screens
- handle changes of `RepeatableActionsField`
- Add `validateRepeatableActions` for validate chosen option and presence of repeatable field 
- Add `getRepeatableFieldAction ` method for getting chosen repeatable action
[UIDATIMP-508](https://issues.folio.org/browse/UIDATIMP-508)
> UIDATIMP-508: Field mappings: Repeatable field dropdown Validation

- CHANGELOG.md
- src/components/ListView/ListView.js
- src/components/SearchAndSort/SearchAndSort.js
- src/components/Spinner/Spinner.js
- src/settings/ActionProfiles/ViewActionProfile.js
- src/settings/FileExtensions/ViewFileExtension.js
- src/settings/JobProfiles/ViewJobProfile.js
- src/settings/MappingProfiles/MappingProfiles.js
- src/settings/MappingProfiles/ViewMappingProfile.js
- src/settings/MatchProfiles/ViewMatchProfile.js
- test/bigtest/interactors/action-profiles/action-profile-details.js
- test/bigtest/interactors/file-extensions/file-extension-details.js
- test/bigtest/interactors/job-profiles/job-profile-details.js
- test/bigtest/interactors/mapping-profiles/mapping-profile-details.js
- test/bigtest/interactors/match-profiles/match-profile-details.js
To provide a full screen view of the field mapping profile View details
- Use  `FullScreenView` component from stripes-data-transfer-components
- add detecting `isMappingProfile` to render Mapping profile details in another way
- update styles
[UIDATIMP-535](https://issues.folio.org/browse/UIDATIMP-535)
> UIDATIMP-535: Field Mapping Profile details: Have view details screen cover the entire screen

- CHANGELOG.md
- src/components/MatchCriterion/edit/MARCFieldSection/MARCFieldSection.js
- src/components/MatchCriterion/edit/MatchCriterion.js
- src/components/MatchCriterion/view/MARCFieldSection/MARCFieldSection.js
- src/utils/constants.js
- src/utils/formValidators.js
- test/bigtest/tests/match-profiles/new-match-profiles-test.js
To update the MARC matching to differentiate wildcard (any) versus [blank] indicators
1. Update validation rules for `MARCFieldSection` component
2. Add `validateMARCFieldInMatchCriterion` validation function
3. Update logic for showing empty field in `MARCFieldSection` component
[UIDATIMP-525](https://issues.folio.org/browse/UIDATIMP-525)
> UIDATIMP-525: Update MARC matching UI to differentiate [any] versus [blank] indicators

- CHANGELOG.md
- src/components/ListTemplate/incomingRecordTypes.js
- src/components/ListTemplate/index.js
- src/components/ListTemplate/matchIncomingRecordTypes.js
- src/components/MatchCriterion/edit/MatchCriterion.js
- src/components/MatchCriterion/view/ViewMatchCriterion.js
- src/components/RecordTypesSelect/RecordTypesSelect.js
- src/components/RecordTypesSelect/components/IncomingRecordMenu.js
- src/settings/MatchProfiles/MatchProfiles.js
- src/settings/MatchProfiles/MatchProfilesForm.js
- src/settings/MatchProfiles/ViewMatchProfile.js
- src/utils/constants.js
- test/bigtest/mocks/form-config-samples.js
- test/bigtest/network/factories/file-extension.js
- test/bigtest/network/factories/match-profile.js
- test/bigtest/network/scenarios/fetch-file-extensions-success.js
- test/bigtest/network/scenarios/fetch-job-profiles-success.js
- test/bigtest/network/scenarios/load-records.js
- test/bigtest/tests/file-extensions/new-file-extensions-test.js
- test/bigtest/tests/match-profiles/new-match-profiles-test.js
- translations/ui-data-import/en.json
To remove the Delimited option from the Match profile, Mapping profile, Job profile and File extension Incoming data types and Remove Static match options from Field mapping Incoming record types.
- Add `matchIncomingRecordTypes` template
- Update all dependencies to `IncomingRecordTypes` template
- Remove `DELIMITED` type from all places
- Update tests
[UIDATIMP-560](https://issues.folio.org/browse/UIDATIMP-560)
[UIDATIMP-561](https://issues.folio.org/browse/UIDATIMP-561)
[UIDATIMP-562](https://issues.folio.org/browse/UIDATIMP-562)
[UIDATIMP-626](https://issues.folio.org/browse/UIDATIMP-626)
> UIDATIMP-560/561/562/626: Update the available Data types and remove Delimited option

- CHANGELOG.md
- src/components/RepeatableActionsField/RepeatableActionsField.js
- src/settings/MappingProfiles/detailsSections/view/HoldingsDetailsSections/AdministrativeData.js
- src/settings/MappingProfiles/detailsSections/view/HoldingsDetailsSections/ElectronicAccess.js
- src/settings/MappingProfiles/detailsSections/view/HoldingsDetailsSections/HoldingsDetails.js
- src/settings/MappingProfiles/detailsSections/view/HoldingsDetailsSections/HoldingsNotes.js
- src/settings/MappingProfiles/detailsSections/view/HoldingsDetailsSections/ReceivingHistory.js
- src/settings/MappingProfiles/detailsSections/view/InstanceDetailsSection/AdministrativeData.js
- src/settings/MappingProfiles/detailsSections/view/InstanceDetailsSection/DescriptiveData.js
- src/settings/MappingProfiles/detailsSections/view/InstanceDetailsSection/InstanceRelationship.js
- src/settings/MappingProfiles/detailsSections/view/ItemDetailSection/AdministrativeData.js
- src/settings/MappingProfiles/detailsSections/view/ItemDetailSection/ElectronicAccess.js
- src/settings/MappingProfiles/detailsSections/view/ItemDetailSection/EnumerationData.js
- src/settings/MappingProfiles/detailsSections/view/ItemDetailSection/ItemNotes.js
- src/settings/MappingProfiles/detailsSections/view/ItemDetailSection/LoanAndAvailability.js
- src/settings/MappingProfiles/detailsSections/view/ViewRepeatableField.js
- src/utils/constants.js
To update the view of the dropdown options for repeatable fields in the Instance, Holding, and Item field mapping profiles.
* Create `ViewRepeatableField` component to render view of the dropdown options for repeatable fields.
* Display value of the dropdown option under a field label.
* If the dropdown option value is equal to `Delete all existing values` then disable displaying of MCL for the field.
[UIDATIMP-555](https://issues.folio.org/browse/UIDATIMP-555)
> UIDATIMP-555: Update the Field mapping View for repeatable fields options

- src/components/FlexibleForm/ControlDecorators/partials/TextDate.js
With the recent, much-needed upgrade to react-overlays, the RootCloseWrapper was changed to a hook. We now re-export it in its component form through `stripes-components`
I'm a bit curious as to how eslint let you get away with such an import - reaching into the directory structure of a dependency that wasn't in the package.json is usually a major gripe.
> Import RootCloseWrapper through stripes

- CHANGELOG.md
- src/settings/MARCFieldProtection/MARCFieldProtection.js
- src/utils/formValidators.js
To fix `validateRequiredFields` function
- Update validation for subfield field for `MARCFieldProtection` component
- revert changes for common `validateRequiredFields` function
[UIDATIMP-645](https://issues.folio.org/browse/UIDATIMP-645)
> UIDATIMP-645: Validation function validateRequiredFields works incorrectly after latest update

- src/settings/MappingProfiles/MappingProfilesForm.js
- translations/ui-data-import/en.json
Purpose
To fix incorrect behaviour of changing type of Field mappings for MARC and add missing label above table
* Add `setTnitalMarcMappingDetails ` method to set default table values
* Add missed text above `Update` table
[UIDATIMP-613](https://issues.folio.org/browse/UIDATIMP-613)
> UIDATIMP-613: Additional fixes

- CHANGELOG.md
- src/components/MARCTableView/MARCTableView.js
- src/components/MARCTableView/MARCTableViewRow.js
- src/components/MARCTableView/MARCTableViewRowContainer.js
- src/components/MatchCriterion/view/MARCFieldSection/MARCFieldSection.js
- src/settings/MappingProfiles/ViewMappingProfile.js
- src/utils/formValidators.js
- src/utils/getTrimmedValue.js
- src/utils/index.js
To indicate that only certain fields in an SRS MARC record should be updated, instead of replacing the entire record, when a user is importing
* Update logic of rendering cells in row to depend on passed headings
* Add `renderMARCTableView` method to `ViewMappingProfile` component
* Add `getCellValue` method to `MARCTableViewRow` component
[UIDATIMP-614](https://issues.folio.org/browse/UIDATIMP-614)
> UIDATIMP-614: MARC Bib field mapping profile: details for Update Selected fields on View screen

- .eslintrc
- CHANGELOG.md
- jest.config.js
- package.json
Remove `import/no-extraneous-dependencies` rule from eslint config and add missed dependencies
[UIDATIMP-639](https://issues.folio.org/browse/UIDATIMP-639)
> UIDATIMP-639: Remove 'import/no-extraneous-dependencies' eslint rule

- CHANGELOG.md
- jest.config.js
When running unit tests there is an error. This is caused because a file with the error is not being correctly transpiled, so jest cannot interpret it properly.
```
/home/jenkins/workspace/folio-org_ui-data-import_PR-687/project/node_modules/ky/index.js:523
export default createInstance();
^^^^^^
SyntaxError: Unexpected token 'export'
at compileFunction (<anonymous>)
2 | 
3 | jest.mock('@folio/stripes/core', () => ({
> 4 |   ...jest.requireActual('@folio/stripes/core'),
|           ^
5 |   stripesConnect: Component => props => <Component {...props} />,
6 | 
7 |   Pluggable: props => <>{props.children}</>,
at Runtime._execModule (node_modules/jest-runtime/build/index.js:1179:56)
at Object.<anonymous> (node_modules/@folio/stripes-core/src/useOkapiKy.js:1:1)
at Object.<anonymous> …
```
> UIDATIMP-667: Fix `SyntaxError: Unexpected token 'export'` error when running unit tests

- CHANGELOG.md
- src/components/MARCTable/MARCTable.js
- src/components/MARCTableView/MARCTableView.js
- src/components/MARCTableView/MARCTableViewRow.js
Position in MCL View is not justified
Fix styles
[UIDATIMP-657](https://issues.folio.org/browse/UIDATIMP-657)
> Settings/Field mapping/MARC mods - "Position" in MCL View is not justified

- CHANGELOG.md
- src/components/RecordTypesSelect/RecordTypesSelect.css
- src/components/RecordTypesSelect/components/RecordItem.js
- src/utils/constants.js
To provide a visual cue for options that are not yet useable in the Job profile
- Add array to `constants` with disabled Folio record types
- Add styles and functionality of disabling options in `RecordItem` component
[UIDATIMP-676](https://issues.folio.org/browse/UIDATIMP-676)
> UIDATIMP-676: Match profile create-edit & view screens: change unusable options to disabled

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/view/MappingMARCBibDetails.js
Render hyphen on the view screen instead of a table when there are no MARC mapping details.
- Check if `marcMappingDetails` is empty.
- If yes - render `<NoValue>` component.
- If no - render `<MARCTableView>` component.
[UIDATIMP-661](https://issues.folio.org/browse/UIDATIMP-661)
> UIDATIMP-661: Render hyphen when MARC mapping details are empty

- CHANGELOG.md
- src/settings/ActionProfiles/ActionProfilesForm.js
To provide a visual cue for options that are not yet useable in the Action profile
- Add functionality of disabling options in `ActionProfilesForm` component
[UIDATIMP-673](https://issues.folio.org/browse/UIDATIMP-673)
> UIDATIMP-673: Action profile create-edit screen: change unusable options to disabled

- CHANGELOG.md
- src/components/ProfileTree/ProfileBranch.js
- src/components/ProfileTree/ProfileLabel.js
- src/components/ProfileTree/ProfileTree.js
- src/settings/JobProfiles/JobProfiles.js
- src/settings/JobProfiles/JobProfilesForm.js
- src/settings/MatchProfiles/MatchProfiles.js
When trying to link a match profile where Existing record field = "Identifier: ..." to a job profile, an error message appears.
- Add missed `resources` prop to `ProfileTree` component
[UIDATIMP-687](https://issues.folio.org/browse/UIDATIMP-687)
> UIDATIMP-687: Fix linking a match profile to a job profile

- src/settings/MatchProfiles/MatchProfilesForm.js
`MatchingFieldsManager` was imported twice.
> only import MatchingFieldsManager once

- CHANGELOG.md
- src/components/ListTemplate/incomingRecordTypes.js
- src/components/RecordTypesSelect/components/IncomingRecordMenu.js
- src/settings/MappingProfiles/MappingProfilesForm.js
- src/utils/constants.js
To provide a visual cue for options that are not yet useable in the Field mapping profile
- Add functionality of disabling options in `IncomingRecordMenu` and `MappingProfilesForm` component
[UIDATIMP-674](https://issues.folio.org/browse/UIDATIMP-674)
> UIDATIMP-674: Field mapping profile create-edit screen: change unuseable options to disabled

- CHANGELOG.md
- src/settings/JobProfiles/JobProfilesForm.js
To provide a visual cue for options that are not yet useable in the Job profile
- Add functionality of disabling options in `JobProfilesForm` component
[UIDATIMP-675](https://issues.folio.org/browse/UIDATIMP-675)
> UIDATIMP-675: Job profile create-edit screen: change unusable options to disabled

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/LoanAndAvailability.js
Due to a [bug in jsx-exlint](https://github.com/jsx-eslint/jsx-ast-utils/issues/103), the changed line causes ESLint to die. The bug [has been fixed](https://github.com/jsx-eslint/jsx-ast-utils/pull/102) but hasn't made its way into a release yet, and it would be really nice to have lint working again!
Refs [UIDATIMP-690](https://issues.folio.org/browse/UIDATIMP-690)
> UIDATIMP-690 prevent ESLint from dying

- CHANGELOG.md
- src/components/MARCTable/MARCTable.js
- src/settings/MappingProfiles/detailsSections/edit/MappingMARCBibDetails.js
When adding subsequent rows to the MARC fields to be updated, the subsequent rows do not default to * for Ind 1, Ind 2, Subfield
- add 'fillNewRowFieldsWithDefaultValue' property to the 'MARCTable' component
- add new logic to 'addNewRow' function
https://issues.folio.org/browse/UIDATIMP-691
> UIDATIMP-691 filling new rows with wildcard symbol

- CHANGELOG.md
- src/components/ListView/ListView.js
- src/settings/FileExtensions/FileExtensions.js
To sort Newly-created file extension settings in alphabetical order
- Set  prop `defaultSort: 'extension',` for `FileExtensions` component
[UIDATIMP-681](https://issues.folio.org/browse/UIDATIMP-681)
> UIDATIMP-681: Newly-created file extension settings do not file in alphabetical order

- CHANGELOG.md
- src/components/MatchCriterion/edit/ExistingRecordSections/ExistingSectionFolio.js
- src/components/MatchCriterion/edit/MatchCriterion.js
When creating a new match profile with existing record type = `Holdings` or `Item` and selecting a match by `Holdings UUID` or `Item UUID` and saving the profile, it is created with a match by `Instance UUID`. It happens because the value for the selected option from a dropdown is retrieved from `formConfig` config by key `id` and for `Instance`, `Holdings` or `Item` this key is the same, so the first entry (for `Instance`) is returned.
- Find the selected option in `formConfig` config by `id` key and `existingRecordType` key so it is unique.
[UIDATIMP-747](https://issues.folio.org/browse/UIDATIMP-747)
> UIDATIMP-747: Fix matching by id for Holdings and Item

- CHANGELOG.md
- src/components/BooleanActionField/BooleanActionField.test.js
To cover <BooleanActionField> component with tests using RTL+Jest.
- Cover `BooleanActionField` with tests
https://issues.folio.org/browse/UIDATIMP-700
> UIDATIMP-700: Cover <BooleanActionField> component with tests

- CHANGELOG.md
- src/routes/ViewAllLogs/ViewAllLogs.js
To have a better UI for loading log entries
As a staff person working with data import logs
I want to be able to scroll through all the logs on the View all log page
So that I can find one that I want even if I don't know the exact name or date
- property INITIAL_RESULT_COUNT has been substituted with RESULT_COUNT_INCREMENT for ViewAllLogs component;
- properties pagingType and pageAmount has been added to ViewAllLogs component configuration
https://issues.folio.org/browse/UIDATIMP-755
> UIDATIMP-755: Add "Load more" button to View all log page

- CHANGELOG.md
- src/components/JobLogsContainer/JobLogsContainer.js
- src/components/ListTemplate/listTemplate.js
- src/components/RecentJobLogs/RecentJobLogs.js
- src/utils/constants.js
on the Data Import landing page, the status sort ascending works, but not descending
custom cell formatter has been applied for status cell
[UIDATIMP-758](https://issues.folio.org/browse/UIDATIMP-758)
> UIDATIMP-758 Status descending sort on Data Import home page not working

- CHANGELOG.md
- src/components/DatePickerDecorator/DatePickerDecorator.js
- src/components/DatePickerDecorator/DatePickerDecorator.test.js
- src/components/TextDate/TextDate.js
To cover `<DatePickerDecorator>` component with tests
[UIDATIMP-704](https://issues.folio.org/browse/UIDATIMP-704)
> UIDATIMP-704: Cover `<DatePickerDecorator>` component with tests

- CHANGELOG.md
- src/components/AcceptedValuesField/AcceptedValuesField.js
- src/components/withReferenceValues/withReferenceValues.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceAdjustments.js
- src/settings/MappingProfiles/detailsSections/utils.js
- src/utils/constants.js
Fund distribution section should be visible only when "Not prorated" option in Pro rate select is selected in Invoice adjustments accordion
- Add `onFieldChange` prop for  `AcceptedValuesField` component to be able to pass additional change handler to `Field`
- Add `handleProRateChange` handler to `InvoiceAdjustments` component
https://issues.folio.org/browse/UIDATIMP-296
> UIDATIMP-802: Fund distribution section should be visible only when Not prorated option in Pro rate select is selected

- CHANGELOG.md
- src/components/UploadingJobsDisplay/UploadingJobsDisplay.js
The data import "secret button" has served its purpose and will now be retired. It uses a different architecture from the other job profiles, and its job profile cannot be retrieved via API. Since the upload area was moved to the top left, it's also easy for a user to accidentally select that option instead of the correct job profile from the list in the center pane.
As a staff person working with uploaded files
I do not want to see the option for the secret button
Removing 'secret button' from template
https://issues.folio.org/browse/UIDATIMP-812
> UIDATIMP-812 Remove "secret button" from Choose jobs screen

- CHANGELOG.md
- src/settings/MARCFieldProtection/MARCFieldProtection.js
- src/utils/constants.js
When trying to set the 005 field to a protected field, it is not allowed
- Add constant MARC_FIELD_PROTECTION_ALLOWED_FIELD_VALUES;
- Update validation logic for validateField
https://issues.folio.org/browse/UIDATIMP-835
> UIDATIMP-835 Allow 005 to be a protected field

- CHANGELOG.md
- src/settings/MappingProfiles/MappingProfiles.js
When we have more than 10 fields protected in MARC field protection Settings, only 10 appear for override in the field mapping profile (bibliographic, updates), with no option to scroll.
- query string has been extended with 'limit' param
https://issues.folio.org/browse/UIDATIMP-849
> UIDATIMP-849 - protection fields in field mapping profile only lists 10

- CHANGELOG.md
- src/settings/MatchProfiles/MatchProfilesForm.js
When a page is resized for a new match profile, all form values are reset.
- Add the `initialValuesEqual` option to the `stripesFinalForm` decorator.
https://issues.folio.org/browse/UIDATIMP-867
> UIDATIMP-867: Match profile: form values are reset on page resize

- CHANGELOG.md
- src/components/OverrideProtectedFieldsTable/OverrideProtectedFieldsTable.js
- src/settings/MappingProfiles/MappingProfilesForm.js
- src/settings/MappingProfiles/ViewMappingProfile.js
- src/settings/MappingProfiles/detailsSections/edit/MappingMARCBibDetails.js
- src/settings/MappingProfiles/detailsSections/view/MappingMARCBibDetails.js
To make the accordions in the MARC update field mapping profile more responsive and efficient
- Split `OverrideProtectedFieldsTable` and `MARCTable` into two different accrodions
https://issues.folio.org/browse/UIDATIMP-858
> UIDATIMP-858: MARC Updates field mapping profile: be able to collapse/expand accordions

- CHANGELOG.md
- src/utils/formValidators.js
Cannot map data from a numeric subfield.
- validation pattern has been extended with numeric values
https://issues.folio.org/browse/UIDATIMP-885
> UIDATIMP-885 856$3 not mapping into holdings record (no numeric subfield mappings are working)

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceLineInformation.js
during profile creation, changing type of FOLIO record leads to error page
Optional chaining operator has been added to releaseEncumbranceCheckbox determination
https://issues.folio.org/browse/UIDATIMP-887
> UIDATIMP-887 FOLIO record type dropdown issue

- CHANGELOG.md
- src/settings/ActionProfiles/ActionProfiles.js
- src/settings/MappingProfiles/MappingProfiles.js
Since the quickMARC derive action profile and field mapping profile should only be linked to each other, suppress them from displaying when associating a user-created action profile with a user-created field mapping profile and vice versa.
Since the quickMARC derive action profile should only be used for the system quickMARC derive job profile, disallow it from being linked to any user-created job profiles.
- extend query string to exclude appropriate profiles
https://issues.folio.org/browse/UIDATIMP-891
https://issues.folio.org/browse/UIDATIMP-892
> UIDATIMP-891 Suppress quickMARC derive action and field mapping profiles from each other's associated profiles

- CHANGELOG.md
- src/settings/JobProfiles/JobProfiles.js
Since the quickMARC derive job profiles is only used by the system (when triggered by an action from quickMARC), it should not display on the Choose jobs page after a user has uploaded a file for import.
- extend query string to exclude appropriate profiles
- 
https://issues.folio.org/browse/UIDATIMP-893
> UIDATIMP-893 Suppress quickMARC derive job profile from the Choose jobs list

- CHANGELOG.md
- test/jest/babel.config.js
Update jest babel config to avoid errors related to: `ReferenceError: React is not defined`
> UIDATIMP-928: Update jest-related configs

- CHANGELOG.md
- src/components/BooleanActionField/BooleanActionField.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/HoldingsNotes.js
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/ItemNotes.js
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/LoanAndAvailability.js
Inventory Holdings and Item records have notes fields which include a checkbox for staff only or not. If a field mapping profile is created, and no value is selected for the "staff only" checkbox, then the import will error. This story adds validation to that portion of the notes field in the field mapping profiles UI, to reduce the chance of making errors when creating or updating a field mapping profile.
- Add `required` prop to the `Field`
https://issues.folio.org/browse/UIDATIMP-920
> UIDATIMP-920: For Holdings and Items, add validation for the "Staff only" field

- CHANGELOG.md
- src/components/DataFetcher/DataFetcher.js
- src/components/RecentJobLogs/RecentJobLogs.js
To ensure that the most recent 25 Imports show on the Data Import landing page
As a staff person working with imported files
I want to see the most recent 25 imports on the Data Import landing page (excluding the Inventory Single Record Imports)
So that I can maintain an understanding of the most recent imports
- request to the job list has been updated to exclude OCLC records 
- filtering for job list has been removed from UI;
https://issues.folio.org/browse/UIDATIMP-950
> UIDATIMP-950 Ensure that the most recent 25 import logs display on the Data Import Landing Page

- CHANGELOG.md
- src/components/MatchCriterion/edit/IncomingSectionStatic/StaticValueDateRange.js
- src/utils/formUtils.js
After editing the match profile the data does not change.
- Add check on date range fields pristine.
- Fix dirty state of date inputs.
https://issues.folio.org/browse/UIDATIMP-951
> UIDATIMP-951: After editing the match profile the data does not change

- CHANGELOG.md
- src/components/ProfileTree/ProfileBranch.test.js
- src/components/ProfileTree/ProfileLabel.test.js
- src/components/ProfileTree/ProfileLinker/LinkerButton.test.js
- src/components/ProfileTree/ProfileLinker/LinkerMenu.test.js
- src/components/ProfileTree/ProfileLinker/LinkerTrigger.test.js
- src/components/ProfileTree/ProfileLinker/ProfileLinker.test.js
- src/components/ProfileTree/ProfileTree.test.js
- test/jest/__mock__/stripesCore.mock.js
Cover <ProfileTree> component with unit tests 
Covered <ProfileTree> component with unit tests using RTL + Jest
https://issues.folio.org/browse/UIDATIMP-718
> UIDATIMP-718: Cover <ProfileTree> component with unit tests 

- CHANGELOG.md
- src/components/ProfileTree/ProfileLinker/ProfileLinker.js
Currently cannot add matches or actions to a MARC or EDIFACT job profile on folio-snapshot or folio-snapshot-load
- workaround to fix UIDATIMP-1002. Removing callback for Dropdown component onToggle
https://issues.folio.org/browse/UIDATIMP-1002
> UIDATIMP-1002 Cannot add matches or actions to a job profile

- CHANGELOG.md
- package.json
It is necessary to add the following "invoice-storage.invoices.item.get", "invoice-storage.invoice-lines.item.get" module permissions to obtain invoice and invoice lines for the JSON screen.
Correspond permissions has been added
> UIDATIMP-1003 Expand module permissions with permissions for retrieving invoice and invoice lines

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceInformation.js
If there are more than 10 acquisitions units for a tenant, the invoice field mapping profile only shows the first 10 in the dropdown list
- limit parameter has been added to correspond request
https://issues.folio.org/browse/UIDATIMP-1008
> UIDATIMP-1008 - Invoice field mapping profile only displays first 10 acq unit values

- CHANGELOG.md
- package.json
Refactor psets to avoid .all permissions from backend modules.
actually we don't have such dependencies in our permissions presets, but we have find few permissions that were added on UI as workaround and currently could be removed
https://issues.folio.org/browse/UIDATIMP-1017
> UIDATIMP-1017 - refactor psets away from backend ".all" permissions

- CHANGELOG.md
- src/components/DataFetcher/DataFetcher.js
There is an error log from mod-source-record-manager while using endpoint "/metadata-provider/jobExecutions":
- third parameter 'encode' for createUrl function for correspond request has been changed to true
https://issues.folio.org/browse/UIDATIMP-1004
> UIDATIMP-1004 - Illegal character in query for mod-source-record-manager

- CHANGELOG.md
- src/components/LogViewer/LogViewer.js
- src/components/LogViewer/LogViewer.test.js
- src/routes/ViewJobLog.js
- src/routes/tests/ViewJobLog.test.js
- src/utils/constants.js
- translations/ui-data-import/en.json
Functionality for new `Authority` toggle button same as for `Holdings` or `Instance`, but needs backend implementation for `metadata-provider/jobLogEntries/` endpoint. It should returns a `relatedAuthorityInfo` object in response.
Issue: [UIDATIMP-1044](https://issues.folio.org/browse/UIDATIMP-1044)
> UIDATAIMP-1044: Add an Authority toggle and show response

- CHANGELOG.md
- src/settings/JobProfiles/ViewJobProfile.js
When a job profile creates or updates an Instance, the log hotlinks for Instance, Holdings, and/or Item record are populated. When a job profile creates or updates a Holdings or Item, without updating an Instance, the Holdings and/or Item log hotlinks are not populated
Request payload now filling with separated parameters instead inside 'query' parameter
https://issues.folio.org/browse/UIDATIMP-1081
> UIDATIMP-1081 Job profiles are showing incorrect info for "Jobs using this profile" accordion

- CHANGELOG.md
- src/components/MatchCriterion/view/IncomingSectionStatic/IncomingSectionStatic.test.js
- src/components/ProfileAssociator/tests/ProfileAssociator.test.js
- src/settings/MatchProfiles/MatchProfilesForm.js
- src/settings/MatchProfiles/MatchProfilesForm.test.js
- Match Profile - Duplicate action does not display Existing record information
- Current code only displays existing record fields when record is being edited. Because `existingRecord` state is assigned intial `existingRecordType` value only in `editing` mode. Also, `existing record field` selection list is populated only in editing mode.
- I added `isDuplicate` to check in `getInitialFields()` function to populate  `existing record field` selection list in `duplicate` mode
- https://issues.folio.org/browse/UIDATIMP-1102
> UIDATIMP-1102: Match Profile - Duplicate action does not display existing record information

- CHANGELOG.md
- src/components/RepeatableActionsField/RepeatableActionsField.js
When you try to add a statistic code while creating a New field mapping profile, the line to enter it is not added on the first click, but the message "One or more values must be added before the profile can be saved." is displayed. To add a line for input, you must press a second time.
- added blur event trigger after option from dropdown has been chosen
> UIDATIMP-1110 - Fix for RepeatableFieldComponent

- CHANGELOG.md
- package.json
- src/settings/MappingProfiles/tests/ViewMappingProfile.test.js
There is any of warning or error messages if the user tries to import a file using the default job profile
Appropriate set of permissions were added to "Data import: all permissions" permissionSet
"converter-storage.jobprofile.get",
"converter-storage.matchprofile.get",
"converter-storage.actionprofile.get",
"converter-storage.mappingprofile.get",
"converter-storage.profileassociation.get"
> UIDATIMP-1040 - File import of the specific file is not works for a user with only "data-import" permissions set

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/AdministrativeData.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/ElectronicAccess.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/HoldingsDetails.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/HoldingsNotes.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/Location.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/ReceivingHistory.js
- src/settings/MappingProfiles/detailsSections/edit/MappingHoldingsDetails.js
- src/settings/MappingProfiles/detailsSections/edit/tests/MappingHoldingsDetails.test.js
- src/settings/MappingProfiles/initialDetails/HOLDINGS.js
To add Data Import support for the Administrative note field that was added to the Inventory Holdings
- 'Administrative note' RepeatableActionsField has been added 
- DTO for HOLDINGS has been updated
https://issues.folio.org/browse/UIDATIMP-1119
> UIDATIMP-1119 - Add Admin note field to the Holdings field mapping profile: Create/Edit

- CHANGELOG.md
- src/routes/JobSummary/JobSummary.js
- src/routes/JobSummary/JobSummary.test.js
Display Authority information on Data import log page
[UIDATIMP-1053](https://issues.folio.org/browse/UIDATIMP-1053)
https://user-images.githubusercontent.com/96055497/163401748-4f611cc9-d267-48d7-8242-49fd6b726e4d.mp4
> UIDATIMP-1053: Display Authority information on Data import log page

- package.json
- Per conversation with Zak Burke, an app will have a (mostly empty) `permSet` like `settings.thenameoftheapp.enabled` that includes `settings.enabled` as the only subPermissions value. That allows the app to show up in the left-hand pane of settings. Additionally, for the list-items `foo` and `bar` in the second pane of settings an app will have `ui-thenameoftheapp.settings.foo` and `ui-thenameoftheapp.settings.bar` that include `settings.thenameoftheapp.enabled` plus additional foo-specific or bar-specific permissions.
> UIDATIMP-1145-FOLLOWUP: Move setting.data-import.enabled to new permSet

- CHANGELOG.md
- src/components/JobLogsContainer/JobLogsContainer.js
-  Change Import log hotlinks to textLink: Landing page
- Use `TextLink` instead of `Button`
- https://issues.folio.org/browse/UIDATIMP-1169
-
> UIDATIMP-1169: Change Import log hotlinks to textLink: Landing page

- CHANGELOG.md
- src/routes/JobSummary/components/RecordsTable.js
- Change Import log hotlinks to textLink: Log details screen
- use `<TextLink />` instead of `<Button />`
- https://issues.folio.org/browse/UIDATIMP-1171
> UIDATIMP-1171: Change Import log hotlinks to textLink: Log details screen

- CHANGELOG.md
- src/components/ProfileAssociator/associatedProfilesColumns.js
- Change associated hotlinks in Match, Action, Field mapping profiles to textLink, in Settings/Data import
- Use `<TextLink/>` instead of `<Button/>`
- https://issues.folio.org/browse/UIDATIMP-1181
width="300" />
> UIDATIMP-1181: Change associated hotlinks in Match, Action, Field mapping profiles to textLink, in Settings/Data import

- CHANGELOG.md
- src/components/ListTemplate/ColumnTemplates/DefaultColumn.js
Change Job profile tree hotlinks to textLink, in Settings/Data import
https://issues.folio.org/browse/UIDATIMP-1180
> UIDATIMP-1180: Change Job profile tree hotlinks to textLink, in Settings/Data import

- CHANGELOG.md
- src/components/ProfileAssociator/associatedProfilesColumns.js
- src/components/TextDate/TextDate.css
- src/components/TextDate/TextDate.js
- prefer @folio/stripes exports to private paths when importing Calendar component
- https://issues.folio.org/browse/UIDATIMP-942
> UIDATIMP-942: Prefer @folio/stripes exports to private paths when importing Calendar component

- CHANGELOG.md
- src/routes/ViewAllLogs/ViewAllLogs.js
View all logs: User filter contains only users displayed on a specific page
Use new API
[UIDATIMP-1178](https://issues.folio.org/browse/UIDATIMP-1178)
https://user-images.githubusercontent.com/100832608/171158272-6d25a00c-0b44-41ab-9c63-13408a21b346.mp4
> UIDATIMP-1178: View all logs: User filter contains only users displayed on a specific page

- CHANGELOG.md
- package.json
- src/components/ImportJobs/ImportJobs.js
- src/components/Jobs/components/Job/Job.js
Create a new Data import UI permission for only viewing app and logs and also fix delete logs permission.
Create a new UI permission on package.json for view only and fix the delete logs permission.
[UIDATIMP-1187](https://issues.folio.org/browse/UIDATIMP-1187)
[UIDATIMP-1144](https://issues.folio.org/browse/UIDATIMP-1144)
> UIDATIMP-1187: Create a new Data import UI permission for only viewing app and logs and fix delete logs permission

- CHANGELOG.md
- src/components/JobLogsContainer/JobLogsContainer.js
- src/components/ListTemplate/ColumnTemplates/CheckboxColumn.js
- src/components/ListTemplate/HeaderTemplates/CheckboxHeader.js
- src/components/ListTemplate/listTemplate.js
- src/components/RecentJobLogs/RecentJobLogs.js
- src/routes/Home.js
- src/routes/tests/Home.test.js
- src/utils/jobLogsListProperties.js
- The "select all items" button does not select all logs after deleting multiple logs from the landing logs page
- Refs: https://issues.folio.org/browse/UIDATIMP-1186
- The problem was after deleting some logs, the logs list `checkboxList` was using was stale because it didn't get updated in `componentDidUpdate()` correctly.
- Add logic to update `checkboxList` list when `job logs` change.
- Disable checkboxes while deletion in progress and until `ui` has been updated.
https://user-images.githubusercontent.com/89512426/172786648-fd26131b-c52f-4726-9ed2-269c9da60c6d.mp4
https://user-images.githubusercontent.com/89512426/172786711-8bf5829f-3d72-4228-b7dc-7575b7c7f47b.mp4
> UIDATIMP-1186: The "select all items" button does not select all logs after deleting multiple logs from the landing logs page

- CHANGELOG.md
- src/settings/MappingProfiles/MappingProfilesForm.js
- src/settings/MappingProfiles/initialDetails/index.js
If a field mapping profile is created by duplicating one of the 'default' field mapping profiles - the 'enabled' indicator on the 'permanentLocationId' field (and the other fields) is set to false. This causes an error during the import - even if the permanentLocationId has been assigned a value.
- Assign the initial `enabled` field for the duplicated mappingDetailes
https://issues.folio.org/browse/UIDATIMP-1191
> UIDATIMP-1191: The enabled indicator for duplicated field mapping fields is set to false

- CHANGELOG.md
- src/routes/ViewAllLogs/ViewAllLogs.js
* Filters on the View all logs page are not updated after logs deletion
* reset `usersList` and `jobProfilesList` after deletion logs using `mutator`
https://issues.folio.org/browse/UIDATIMP-1219
https://user-images.githubusercontent.com/85172747/180396577-9486b5e9-a49a-4f36-b02c-b2824d642e16.mp4
> UIDATIMP-1219: View all logs: filters are not updated after logs deletion

- CHANGELOG.md
- src/components/Jobs/Jobs.js
- src/routes/ViewAllLogs/ViewAllLogs.js
- View all logs: User and Job filter contains only 10 records
- The problem was that by default `endpoint` returns `10` records.
- Increase `limit` of records per request.
- https://issues.folio.org/browse/UIDATIMP-1220
> UIDATIMP-1220: View all logs: User and Job filter contains only 10 records

- CHANGELOG.md
- src/components/Jobs/Jobs.js
- src/components/Jobs/Jobs.test.js
- Remove `Preview` section from landing page.
- Remove `PreviewJobs` component and refactor tests.
- https://issues.folio.org/browse/UIDATIMP-1218
> UIDATIMP-1218: Make UI changes to the Data Import landing page

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceAdjustments.js
- src/settings/MappingProfiles/detailsSections/utils.js
- src/utils/constants.js
- When `Pro rate` field has `Not prorated` value, hide `Separate from` value from `Relation to total` field list.
- When `Relation to total` field has `Separate from` value, hide `Not prorated` value from `Pro rate` list.
- Also, I found a bug with `Add fund distribution button`. The problem is that when there are more than 1 `Invoice adjustments` and one of them enable `Add fund distribution button`, other `adjustments`'s buttons will be enabled even though others don't enable their buttons.
- Remove shared state `isFundDistribution` which caused shared state problem
- Scope field values and fund distribution button logic in `renderAdjustment` function.
- https://issues.folio.org/browse/UIDATIMP-1223
https://user-images.githubusercontent.com/89512426/181759221-d027dd85-c295-4aea-baac-82ae …
> UIDATIMP-1223: Change options for invoice level adjustments in Invoice field mapping

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceInformation.js
- The Batch group `Accepted values` dropdown has a limit of 10 records, but it should show all values.
- Make `limit` 500 records.
- https://issues.folio.org/browse/UIDATIMP-1230
> UIDATIMP-1230: Field Mapping profile: "Batch group field" contains only 10 records

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceInformation.js
- The 'Accepted values' dropdown lists for Acquisitions unit and Batch group are not in alphabetical order in the Invoice field mapping profile. All dropdown lists in field mapping profiles should be in alphabetical order unless otherwise specified.
- Add search param to get the sorted list of records from the back-end.
- https://issues.folio.org/browse/UIDATIMP-1236
> UIDATIMP-1236: Acq unit and Batch group dropdown lists should be in alphabetical order

- CHANGELOG.md
- package.json
[UIDATIMP-1317](https://issues.folio.org/browse/UIDATIMP-1317)
> UIDATIMP-1317: Upgrade moment from 2.24.0 to >= 2.29.4

- CHANGELOG.md
- package.json
[UIDATIMP-1323](https://issues.folio.org/browse/UIDATIMP-1323)
> UIDATIMP-1323: Loose plugin dependencies permit incompatible versions

- package.json
- test/jest/__mock__/index.js
- test/jest/__mock__/stripesComponents.mock.js
- test/jest/__mock__/stripesConfig.mock.js
- test/jest/__mock__/stripesCore.mock.js
- test/jest/__mock__/stripesSmartComponents.mock.js
Mock components using webpack's context since it's not available when components aren't being pulled through webpack.
This doesn't fix _all_ the webapack context errors, but it makes a significant dent, changing the stats from 
```
Test Suites: 115 failed, 41 passed, 156 total
Tests:       116 passed, 116 total
```
to 
```
Test Suites: 71 failed, 1 skipped, 84 passed, 155 of 156 total
Tests:       12 failed, 12 skipped, 413 passed, 437 total
```
I've sunk enough time into this already; the rest is up to you. 
Additionally, there are a few components here that rely on `ACTION_TYPES` being exported from `stripes-data-transfer-components` alongside `FOLIO_RECORD_TYPES`, but it isn't and there is no mention of pending work in SDTC in the PR description :/ 
If you have plans to make that …
> avoid webpack's context

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/POLineDetails.js
- src/settings/MappingProfiles/detailsSections/view/OrderDetailsSection/OrderInformation.js
- src/settings/MappingProfiles/detailsSections/view/OrderDetailsSection/POLineDetails.js
To display the actual `PO lines limit` value from Order Settings on the view and create/edit screen. To send the `Receiving workflow` field value wrapped in quotes.
- Wrap the `Receiving workflow` field value in quotes before sending to BE
- Fetch and display `PO lines limit` value from Order Settings
https://issues.folio.org/browse/UIDATIMP-1348
> UIDATIMP-1348: Receiving value disappears from Order field mapping profile after default order line limit updated

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/FundDistribution.js
For the Order field mapping profile's Expense class field, when displaying the values in the dropdown list or in the field mapping field, the expense class codes do not display - only the expense class names. This applies to the Create/Edit screen and the View screen for the Order field mapping profile.
- Add `optionTemplate` to show the correct format of options.
https://issues.folio.org/browse/UIDATIMP-1368
> UIDATIMP-1368: Order field mapping profile: Show the expense class and code when default expense class is selected

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/FundDistribution.js
For the Order field mapping profile's Fund field, when displaying the values in the dropdown list or in the field mapping field, the fund codes do not display - only the fund names. This applies to the Create/Edit screen and the View screen for the Order field mapping profile.
- Add `optionTemplate` to show the correct format of options.
https://issues.folio.org/browse/UIDATIMP-1367
> UIDATIMP-1367: Order field mapping profile: Show the fund and code when default fund is selected

- CHANGELOG.md
- src/settings/ActionProfiles/EditActionProfile/EditActionProfile.js
- src/settings/MappingProfiles/EditMappingProfile/EditMappingProfile.js
- src/utils/formUtils.js
When updating action/mapping profile that is already linked with another profile the "parentProfiles" and "childProfiles" properties are sent populated with read-only data to the back-end, which causes profile to increase in size.
- Omit "parentProfiles" and "childProfiles" properties on form submit
https://issues.folio.org/browse/UIDATIMP-1369
> UIDATIMP-1369: "parentProfiles" and "childProfiles" properties are populated on profile update that causes to size-bloat

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/MappingOrderDetails.js
To correct the Material supplier and Access provider details in the Data Import field mapping Edit screen for Orders and Order line to display the organization name instead of UUID.
- Do not trim quotes of field value to match the pattern
https://issues.folio.org/browse/UIDATIMP-1371
> UIDATIMP-1371: Order line field mapping: Fix organizations on edit screen

- CHANGELOG.md
- src/components/BooleanActionField/BooleanActionField.js
- src/components/BooleanActionField/BooleanActionField.test.js
- src/components/RepeatableActionsField/RepeatableActionsField.js
- src/components/RepeatableActionsField/RepeatableActionsField.test.js
- src/routes/JobSummary/components/RecordsTable.js
- src/routes/JobSummary/components/RecordsTable.test.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/AdministrativeData.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/ElectronicAccess.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/HoldingsDetails.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/HoldingsNotes.js
- src/settings/MappingProfiles/detailsSections/edit/HoldingsDetailsSections/ReceivingHistory.js
- src/settings/MappingProfiles/detailsSections/edit/InstanceDetailsSections/AdministrativeData.js
- src/settings/MappingProfiles/detailsSections/edit/InstanceDetailsSections/Contributor.js
- src/settings/MappingProfiles/detailsSections/edit/InstanceDetailsSections/DescriptiveData.js
- src/settings/MappingProfiles/detailsSections/edit/InstanceDetailsSections/InstanceNotes.js
- src/settings/MappingProfiles/detailsSections/edit/InstanceDetailsSections/InstanceRelationship.js
- src/settings/MappingProfiles/detailsSections/edit/InstanceDetailsSections/TitleData.js
- src/settings/MappingProfiles/detailsSections/edit/InvoiceDetailSection/InvoiceLineFundDistribution.js
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/AdministrativeData.js
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/ElectronicAccess.js
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/EnumerationData.js
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/ItemNotes.js
- src/settings/MappingProfiles/detailsSections/edit/ItemDetailSection/LoanAndAvailability.js
- src/settings/MappingProfiles/detailsSections/edit/MappingInstanceDetails.js
*  For field mappings for the item, holdings, and instance, for the suppress from discovery, staff suppress and previously held for the instance, and any drop down that has "Delete all existing values", once this is selected, it is impossible to go back to the default. This is especially a problem when you duplicate a field mapping or just need to mistakenly selected something and need to go back to the default.
* In `BooleanActionField ` component when select default value, set `null` for the `booleanFieldAction` field
* In `RepeatableActionsField` component when select default value, set initial values for selected field
[UIDATIMP-1357](https://issues.folio.org/browse/UIDATIMP-1357)
https://user-images.githubusercontent.com/85172747/217835756-16a2cc07-7bcf-4887-bd2a-4b7a69d62b5d.mp4
> UIDATIMP-1357: Add ability to go back to defaults in Data Import Field Mappings (Item, Holdings, Instance)

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/OrderInformation.js
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/tests/OrderInformation.test.js
- translations/ui-data-import/en.json
* The behavior of the PO status field and Inventory interactions can be confusing. Add an information icon that helps to explain the behavior
* Added `InfoPopover` to the label with the defined text
[UIDATIMP-1397](https://issues.folio.org/browse/UIDATIMP-1397)
> UIDATIMP-1397: Add info icon to the Purchase order status field

- CHANGELOG.md
- test/jest/__mock__/index.js
- test/jest/__mock__/reactVirtializedAutoSizer.mock.js
A bunch of Jest unit tests started to fail during the build on Github so PRs cannot be merged.
After an investigation was figured out that `react-virtualized-auto-sizer` module should be mocked for all tests.
https://issues.folio.org/browse/UIDATIMP-1422
> UIDATIMP-1422: Mock `react-virtualized-auto-sizer` module for unit tests

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/EResourcesDetails.js
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/Location.js
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/PhysicalResourceDetails.js
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/tests/PhysicalResourceDetails.test.js
If the Order status in the field mapping profile is Open, the Holdings and Item creation will be controlled by the Import job profile, rather than the Create inventory fields of the POL. Inactivate Locations and Material Type fields, and then the system will automatically populate them appropriately, based on the details of mapping profiles included in the job profile.
- Disable Locations repeatable fields and Material type fields when PO status field value is "Open"
https://issues.folio.org/browse/UIDATIMP-1417
> UIDATIMP-1417: Order field mapping profile: Inactivate Locations and Material Types fields when Order status is Open

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/utils.js
- src/settings/MappingProfiles/detailsSections/view/OrderDetailsSection/CostDetails.js
If an Order field mapping profile is created with a discount indicating currency instead of percentage, the user sees $ on the View screen, no matter which currency is indicated.
- Pass `currency` arg to the `renderAmountValue` func to render currency symbol next to `Discount` value
https://issues.folio.org/browse/UIDATIMP-1405
> UIDATIMP-1405: Order field mapping profile: Fix the View UI for Discount Currency

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/view/OrderDetailsSection/FundDistribution.js
If an Order field mapping profile is created with a fund code section, the user sees $ next to the value, no matter which currency was selected, and whether % or currency was selected.
- Pass `currency` arg to `renderAmountValue` func to render currency symbol next to `Value`
- Add `distributionType` to repeatable fields map
https://issues.folio.org/browse/UIDATIMP-1404
> UIDATIMP-1404: Order field mapping profile: Fix the View UI for Fund value % and Currency

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/Location.js
To activate "Location" field when PO status is "Open".
- Remove `canAdd` condition from Locations field and do not clean the field when status is Open
https://issues.folio.org/browse/UIDATIMP-1429
> UIDATIMP-1429: Activate "Location" field for Open Order field mapping

- CHANGELOG.md
- src/components/FieldOrganization/FieldOrganization.js
- src/components/ProfileTree/ProfileLinker/ProfileLinker.test.js
- src/routes/JobSummary/components/RecordsTable.test.js
- src/settings/FileExtensions/FileExtensionForm.test.js
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/OrderInformation.js
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/tests/OrderInformation.test.js
- src/utils/shapes.js
- translations/ui-data-import/en.json
Importer cannot create an order or invoice for a designated acquisitions unit unless the user is a member of that acquisitions unit. This story adds an info icon to the Order field mapping profile to make that more clear
- Render info icon next to acq units field
- Add unit tests
- Test tests warnings and adjust prop types
https://issues.folio.org/browse/UIDATIMP-1426
> UIDATIMP-1426: Order field mapping: Add info icon to the Acq unit field

- CHANGELOG.md
- src/routes/JobSummary/components/SummaryTable.js
Format values in the summary table with <NumberFormat> in order to display them in a locale-friendly way.
- Render cell content with FormattedNumber
https://issues.folio.org/browse/UIDATIMP-1459
> UIDATIMP-1459: Job summary - format numbers in summary table

- CHANGELOG.md
- src/utils/tests/xhr.test.js
- src/utils/xhr.js
* Support 2 types of error responses (`application/json` and `text/plain`)
[UIDATIMP-1465](https://issues.folio.org/browse/UIDATIMP-1465)
> UIDATIMP-1465: Allow to handle text/plain content type when error occurs

- package.json
- src/components/DataFetcher/DataFetcher.js
- src/components/DataFetcher/DataFetcher.test.js
- src/components/JobLogsContainer/JobLogsContainer.js
- src/components/JobLogsContainer/JobLogsContainer.test.js
- src/components/Jobs/Jobs.test.js
- src/components/Jobs/components/Job/Job.css
- src/components/Jobs/components/Job/Job.js
- src/components/Jobs/components/Job/jobExecutionPropTypes.js
- src/utils/compositeJobStatus.js
- src/utils/jobLogsListProperties.js
- test/jest/babel.config.js
- translations/ui-data-import/en.json
- translations/ui-data-import/en_GB.json
- translations/ui-data-import/en_SE.json
- translations/ui-data-import/en_US.json
[UIDATIMP-1466](https://issues.folio.org/browse/UIDATIMP-1466)
and
[UIDATIMP-1464](https://issues.folio.org/browse/UIDATIMP-1464)
Jobs-in-progress cards present data regarding the progress of a running job. With the addition of file-splitting/submission of multiple jobs, we consolidate multiple child job entities to a single card that displays the number of file slices remaining to be processed, the number of finished slices, errored slices, and canceled/discarded slices.
The job log display is also rendered with a 'Job parts' column when the configuration is active.
The query needed to be adjusted to include 'subordinationTypeNotAny=COMPOSITE_CHILD' to pull down the composite job, as well as 'subordinationTypeNotAny=COMPOSITE_PARENT' for the job logs listing.
If the 'job' data for the …
> UIDATIMP-1466 Add composite job details to Job component

- src/index.js
- src/settings/JobProfiles/ViewJobProfile/ViewJobProfile.js
- src/settings/JobProfiles/tests/ViewJobProfile.test.js
Displays the "Job parts" column in the data-import settings Job Profile detail view.
[UIDATIMP-1467](https://issues.folio.org/browse/UIDATIMP-1467)
This column is conditionally displayed based on the objectStorage capability/multipart job splitting. I moved the settings view into the children of the context provider to receive the value from there rather than rendering multiple, separate context providiers.
> UIDATIMP-1467 display jobParts column in Jobs using this profile section

- src/components/UploadingJobsDisplay/UploadingJobsDisplay.js
- src/utils/multipartUpload.js
- src/utils/tests/multipartUpload.test.js
[UIDATIMP-1509](https://issues.folio.org/browse/UIDATIMP-1509)
Since we're using S3 storage to process the files here forward, it only makes sense that the system retain the name as S3 knows it. vs the original filename.
> UIDATIMP-1509 Update 'name' field in uploadDefinition to reflect object storage.

- CHANGELOG.md
- src/routes/JobSummary/components/cells/HoldingsCell.js
- src/routes/JobSummary/components/cells/ItemCell.js
- src/routes/JobSummary/components/utils.js
* When user clicks on holdings and item hotlink, send `state` prop with current tenantId
[UIDATIMP-1551](https://issues.folio.org/browse/UIDATIMP-1551)
https://github.com/folio-org/ui-data-import/assets/85172747/9d949b24-8de6-4999-b811-a3e23b3a30da
> UIDATIMP-1551: Remove error message after clicking on the link in holdings and item column

- CHANGELOG.md
- src/routes/JobSummary/JobSummary.js
- src/routes/JobSummary/JobSummary.test.js
- translations/ui-data-import/en.json
The **'[number of records] - records found'** instead of the **'[number of records] - errors found'** subtitle is displayed after clicking on the textLink error counter.
- Display the correct translations key
https://issues.folio.org/browse/UIDATIMP-1549
> UIDATIMP-1549: The '[number of records] - records found' subtitle is displayed after clicking on the textLink error counter

- CHANGELOG.md
- src/components/DataFetcher/DataFetcher.js
- src/components/DataFetcher/DataFetcher.test.js
https://issues.folio.org/browse/UIDATIMP-1557
Adjust code to display loading spinners rather than the "No records found" messages.
> UIDATIMP-1557 long loading of data on UI-data import landing page.

- CHANGELOG.md
- src/components/Jobs/Jobs.test.js
- src/components/Jobs/components/Job/Job.js
https://issues.folio.org/browse/UIDATIMP-1563
It was difficult to differentiate between "failed" jobs and jobs "completed with errors" from the level of Composite Jobs, so the overlap in numbers was confusing for users. We opted to just remove the failed jobs line from the card details altogether.
Also, the 'Job parts processed' field was not accounting for failed jobs in its 'processed' number, so now those number make better sense since both processed and 'error' status jobs are considered.
After:
> UIDATIMP-1563 - remove failed jobs listing form composite job details. Include failed jobs in part calculation.

- CHANGELOG.md
- src/settings/JobProfiles/ViewJobProfile/ViewJobProfile.js
- src/settings/JobProfiles/tests/JobProfiles.test.js
- src/settings/JobProfiles/tests/ViewJobProfile.test.js
https://issues.folio.org/browse/UIDATIMP-1562
The Job Profile view in settings displayed multiple links for assocated jobs. This was confusing as some links contained the link to download the split source file, and others did not...
The approach was to adjust the query for the items to include only the child jobs - same behavior as the Job Log.
before:
after:
> UIDATIMP-1562 - Job Profile view displaying multiple links

- CHANGELOG.md
- src/components/ProfileTree/ProfileTree.js
- Order field is not correctly set, rollback changes to fix he issue
https://issues.folio.org/browse/UIDATIMP-1571
> UIDATIMP-1571: Order field is nor populated during linking/unlinking profiles to job profile

- CHANGELOG.md
- src/utils/constants.js
* Since `holdingsRecord.json` has been moved to `holdings-storage/holdingsRecord.json` we need to change path on UI respectively
[UIDATIMP-1576](https://issues.folio.org/browse/UIDATIMP-1576)
> UIDATIMP-1576: Change path for holdingsRecord.json

- CHANGELOG.md
- src/components/Jobs/components/Job/Job.css
- src/components/RecordTypesSelect/RecordTypesSelect.css
- src/components/UploadingJobsDisplay/components/FileItem/FileItem.css
https://issues.folio.org/browse/UIDATIMP-1577
In the future, we would like to remove one of our out-dated postcss-plugins - `postcss-color-function` - the native `color()` function has changed since then - it is no longer used for color manipulations or blending.
The functionality has been replaced in spec by CSS color-module 5's [relative color syntax](https://developer.chrome.com/blog/css-relative-color-syntax).
This will require the work from https://github.com/folio-org/stripes-webpack/pull/133 for firefox support.
> UIDATIMP-1577 Refactor css away from color() function

- CHANGELOG.md
- src/components/ListView/ListView.js
- src/settings/ActionProfiles/ActionProfilesForm.js
- src/settings/ActionProfiles/ViewActionProfile/ViewActionProfile.js
- src/settings/DataImportSettings/DataImportSettings.js
- src/settings/FileExtensions/FileExtensionForm.js
- src/settings/FileExtensions/ViewFileExtension/ViewFileExtension.js
- src/settings/JobProfiles/JobProfilesForm.js
- src/settings/JobProfiles/ViewJobProfile/ViewJobProfile.js
- src/settings/MARCFieldProtection/MARCFieldProtection.js
- src/settings/MappingProfiles/MappingProfilesForm.js
- src/settings/MappingProfiles/ViewMappingProfile/ViewMappingProfile.js
- src/settings/MatchProfiles/MatchProfilesForm.js
- src/settings/MatchProfiles/ViewMatchProfile/ViewMatchProfile.js
- translations/ui-data-import/en.json
* Added `Inventory settings - <<selected page name>> - FOLIO` title for each page
* When view the profile, the title is in format `Inventory settings - <<selected page name>> - <<profile name>> - FOLIO`
* When create a new profile, the title is in format `Inventory settings - <<selected page name>> - Create - FOLIO`
* When edit an existing profile, the title is in format `Inventory settings - <<selected page name>> - Edit <<profile name>> - FOLIO`
* When duplicate an existing profile, the title is in format `Inventory settings - <<selected page name>> - Duplicate <<profile name>> - FOLIO`
[UIDATIMP-1578](https://issues.folio.org/browse/UIDATIMP-1578)
https://github.com/folio-org/ui-data-import/assets/85172747/15f409dc-011e-448c-a3ad-5ff0e329df9f
> UIDATIMP-1578: Add title for each page in Data import  settings

- CHANGELOG.md
- src/settings/MatchProfiles/MatchProfiles.js
- src/settings/MatchProfiles/MatchProfiles.test.js
System should be updated to allow Default Inventory Single Record Match profiles to be:
- Viewable
- Linkable to Job Profiles
- but NOT be Editable
Remove filtered by id default match profiles from the query.
https://folio-org.atlassian.net/browse/UIDATIMP-1521
> UIDATIMP-1521: Not able to use system generated Match profiles

- CHANGELOG.md
- src/components/ProfileAssociator/AssociatedList.js
* `Selected` column is not used in associated profiles list, so it'd be better to remove it.
[UIDATIMP-1607](https://folio-org.atlassian.net/browse/UIDATIMP-1607)
https://github.com/folio-org/ui-data-import/assets/85172747/705edbe9-50e8-46b2-aa64-b40faeadf339
https://github.com/folio-org/ui-data-import/assets/85172747/6bd2efc5-3e8a-436f-9e6a-a9d131bb9be0
> UIDATIMP-1607: Remove `selected` column from associated profiles list

- CHANGELOG.md
- src/routes/JobSummary/components/RecordsTable.js
- src/routes/JobSummary/components/cells/ErrorCell.js
- src/routes/JobSummary/components/cells/HoldingsCell.js
- src/routes/JobSummary/components/cells/tests/ErrorCell.test.js
The 'Error' status is not displayed in "Error" column for the same row as Items with status "No action".
- the root 'error' could be empty but some entities could still contain an error, so removed check for the root `error`.
https://folio-org.atlassian.net/browse/UIDATIMP-1619
> UIDATIMP-1619: The 'Error' status is not displayed in "Error" column for the same row as Items with status "No action"

- src/routes/JobSummary/components/RecordsTable.js
- src/routes/JobSummary/components/cells/ErrorCell.js
- src/routes/JobSummary/components/cells/tests/ErrorCell.test.js
* If there's no error in `ErrorCell` component we should return an empty string
[UIDATIMP-1619](https://folio-org.atlassian.net/browse/UIDATIMP-1619)
https://github.com/folio-org/ui-data-import/assets/85172747/ed347ffc-5581-4760-ad28-54fed28485f0
> UIDATIMP-1619: The 'Error' status is not displayed in "Error" column for the same row as Items with status "No action" (follow-up)

- CHANGELOG.md
- src/settings/MappingProfiles/detailsSections/edit/OrderDetailSection/PhysicalResourceDetails.js
To align with decisions made to address MODORDERS-1090, we need to update Order mapping rules so that if Purchase Order Status is set to 'Open', then Material Type field will not be greyed out and will remain mappable.
- Do not disable 'Material type' field when PO status is 'Open'
https://folio-org.atlassian.net/browse/UIDATIMP-1626
> UIDATIMP-1626: Update Order mapping rules to allow Material Type mapping when Purchase Order Status set to 'Open'

- CHANGELOG.md
- src/settings/JobProfiles/JobProfilesForm.js
When you duplicate a job profile that has a match profile and then add more than one action, when you save that job, one of the actions isn’t saved.
- Omit `profileWrapperId` fields for profiles that have been duplicated
https://folio-org.atlassian.net/browse/UIDATIMP-1633
> UIDATIMP-1633: Changes made during duplication of a job with a match profile are not saved

- CHANGELOG.md
- src/components/ListView/ListView.test.js
- src/components/MatchCriterion/edit/ExistingRecordSections/ExistingSectionFolio.test.js
- src/routes/ViewAllLogs/ViewAllLogs.js
- src/routes/ViewAllLogs/ViewAllLogs.test.js
- src/settings/MatchProfiles/MatchProfiles.test.js
* Transform `ViewAllLogs` component into the functional one in order to send one request during using pagination.
[UIDATIMP-1630](https://folio-org.atlassian.net/browse/UIDATIMP-1630)
> UIDATIMP-1630: Transform `ViewAllLogs` component into the functional one

- CHANGELOG.md
- package.json
* Add `source-storage.sourceRecords.get` permission to **Data import: Can view only** and **Data import: Can upload files, import, and view logs** in order to see SRS MARC logs. [Required permission to call the endpoint](https://github.com/folio-org/mod-source-record-storage/blob/fb4dc58066a0f7ae14671a3a56ea8fd0c815b209/descriptors/ModuleDescriptor-template.json#L159)
[UIDATIMP-1652](https://folio-org.atlassian.net/browse/UIDATIMP-1652)
> UIDATIMP-1652: Add missing `source-storage.sourceRecords.get` permission

- CHANGELOG.md
- src/routes/ViewAllLogs/ViewAllLogsFilters.js
* Display placeholder in `Job profile` and `User` filters on the `View all` page after clicking on `Reset all` button.
* Added `formatter` prop to filters. When user clicks "Reset all" or resets particular filter then display placeholder.
[UIDATIMP-1675](https://folio-org.atlassian.net/browse/UIDATIMP-1675)
https://github.com/user-attachments/assets/b1514d49-a100-409f-bcf6-2c17e6742ed3
> UIDATIMP-1675: Display placeholder in `Job profile` and `User` filters on the View all page after clicking on `Reset all` button

- CHANGELOG.md
- src/settings/JobProfiles/ViewJobProfile/ViewJobProfile.js
* `defaultProps` will be removed from function components in place of ES6 default parameters. Class components will continue to support `defaultProps` since there is no ES6 alternative.
* Removed `defaultProps` in `ViewJobProfileComponent` component
[UIDATIMP-1634](https://folio-org.atlassian.net/browse/UIDATIMP-1634)
> UIDATIMP-1634: Refactor away from default props for functional components

- CHANGELOG.md
- src/settings/MappingProfiles/MappingProfilesForm.js
- src/settings/MappingProfiles/tests/MappingProfilesForm.test.js
* Allow central tenant to create filed mapping profile for Orders and Invoices
[UIDATIMP-1685](https://folio-org.atlassian.net/browse/UIDATIMP-1685)
> UIDATIMP-1685: Allow central tenant to create filed mapping profile for Orders and Invoices

- CHANGELOG.md
- src/settings/MatchProfiles/MatchProfiles.js
- src/utils/fetchJsonShemas.js
- src/utils/tests/fetchJsonSchemas.test.js
While troubleshooting an issue in the Eureka-bugfest environment, we ran across a [bit of code in ui-data-import](https://github.com/folio-org/ui-data-import/blame/f7b36a39ac5db4e3a5d71f42f120f101e97f1009/src/settings/MatchProfiles/MatchProfiles.js#L240-L249) that queries Okapi for the tenant’s currently-installed modules with a manifest like:
`_/proxy/tenants/${tenant}/modules`;
This same data is available on stripes at stripes.discovery.modules . The discovery process in Eureka is quite different than in legacy FOLIO, with different endpoints etc etc, but all that logic is consolidated within stripes-core at present. If we can leverage the discovery data attached to stripes instead of making a query, then we can keep it that way and avoid the need for Eureka-specific code to pollute …
> UIDATIMP-1686: Replace `_/proxy/tenants/${tenant}/modules` request with `stripes.discovery.modules` object

- CHANGELOG.md
- src/components/Jobs/components/Job/Job.js
In rare cases, the progress bar goes above 100% when a job is stuck in the running column. It would be better to fix this on the BE side, but was decided to add check on UI and show 100% if BE sends progress over 100.
- Show 100% if current progress is > 100.
https://folio-org.atlassian.net/browse/UIDATIMP-1691
> UIDATIMP-1691: Fixed progress bar goes above 100% when job is stuck in running column

- .eslintrc
- CHANGELOG.md
- package.json
- src/components/TextDate/TextDate.test.js
[UIDATIMP-1705](https://folio-org.atlassian.net/browse/UIDATIMP-1705)
[UIDATIMP-1706](https://folio-org.atlassian.net/browse/UIDATIMP-1706)
> UIDATIMP-1705: Migrate `react-intl` and `stripes` dependencies

- src/components/TextDate/TextDate.test.js
TEXTDATE
Who is it in the test that calls on me?
I see a test fail when clicking two-three.
Cry "TextDate". Speak. TextDate is turned to hear.
SOOTHSAYER
Beware the twenty-third of February, twenty-twenty-five!
TEXTDATE
What rot is that?
BRUTUS
A soothsayer bids you, beware February 23.
TEXTDATE
But only in the year two-oh-two-five?
Set him before me. Let me see his face.
CASSIUS
Fellow, come from the throng. Look upon TextDate.
TEXTDATE
What sayst though to me now? Speak once again.
SOOTHSAYER
This is kind of fun, actually. March 2023, not a leap year, starts on a Saturday, so when we show a calendar in a US-English locale where the week starts on a Sunday, that means we will include six dates from the previous month, and during March, 2025, that means we will include February 23-28. …
> UIDATIMP-1715 make TextDate.test.js robust to March, 2025
